- PowerValidatedSolutions.psm1
Updated variable $contentLibraryUrl to $subscriptionUrl to fix the following error message when running the Add-ContentLibrary command.
Error at script line 1949
Relevant Command: Invoke-RestMethod -uri $contentLibraryUrl -method Get | Out-null
Error Message: Cannot validate argument on parameter 'uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again
Signed-off-by: stuart_tormey <stuart_tormey@hotmail.co.uk>
> Fix for missing URI in Add-ContentLibrary

- PowerValidatedSolutions.psm1
Updated like statement variable as when using a workload domain name that does not match anything within the fqdn of the vCenter for the WLD, the command will not work with the following error.
Error at Script Line 2618
Relevant Command: New-VIPermission -Server $vcenter.fqdn -Role $role -Principal $principal -Entity (Get-Folder "Datacenters" -Type Datacenter | Where-Object {$_.Uid -like ""+$workloaddomain+""}) | Out-Null
Error Message: Cannot process argument transformation on parameter 'Entity'. Object reference not set to an instance of an object.
An example would be a domain name of "management" and a fqdn of "vcsa-01.mydomain.local", this causes the like statement to fail.
If you have a domain name of "wld1" and an fqdn of "wld1.mydomain.local", the command would work.
If you run …
> Fix for Set-vCenterPermission/New-VIPermission

- PowerValidatedSolutions.psm1
- Renamed to `Get-CloudProxy`
- Added `-environment` switch to support Production and Staging VMC
- Added support for both Cloud Proxy and Cloud Extensibility Proxy
- Added support for either downloading or simply providing the URL path
- Added support for downloading on Core (Linux, Windows and Mac)
- Removed default environment from Request-CSPToken
Closes #32 
> feat: Add support for downloading the Cloud Proxy and Cloud Extensibility Proxy from VMware Cloud

- PowerValidatedSolutions.psm1
Add 2 cmdlets
- `Get-ESXiPasswordPolicy`
- `Get-VCServerPasswordPolicy`
This cmdlets are used return the password expiration policy for an ESXi host and vCenter Server instance in number of days.
Signed-off-by: Kevin Teng <kteng@vmware.com>
Issue Number: #31 
> feat: Add support to return the ESXi host and vCenter Server password policy

- PowerValidatedSolutions.psm1
This PR adds more detailed error messages for Add-SupervisorClusterLicense.
For `Add-SupervisorClusterLicense`: changed `Write-Error` + `break` for script halting errors to use the PowerShell native `$PSCmdlet.ThrowTerminatingError()` method along with additional context added for each specific error message.
None
None
> refactor: update errors for `Add-SupervisorClusterLicense`

- PowerValidatedSolutions.psm1
Adds three cmdlets for managing the basic configuration of vRealize Automation's integration with vRealize Log Insight.
- `Get-vRAvRLIConfig`
- `Set-vRAvRLIConfig`
- `Remove-vRAvRLIConfig`
```powershell
PS F:\> Set-vRAvRLIConfig -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -rootPass VMw@re1! -protocol HTTP
Setting the vRealize Automation integration with vRealize Log Insight: SUCCESSFUL
PS F:\> Set-vRAvRLIConfig -server …
```
> feat: enable vrli log configuration in vra

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added Add-VdsPortGroup to create a vSphere Distributed port group
- Added Undo-VdsPortGroup to remove vSphere Distributed port group
- Added Add-VrmsNetworkAdapter to create a new adapter in vSphere Replication
- Added Add-SrmLicenseKey to add a license to single vCenter/Site Recovery Manager
- Added Undo-SrmLicenseKey to remove a license to single vCenter/Site Recovery Manager
Issue Number:
- Closes #156 
- Closes …
> Add Shared Functions for vSphere Distributed port group and New Add License for Site Recovery Manager

- CHANGELOG.md
- PowerValidatedSolutions.psm1
Added `Add-EsxiVMkernelPort` cmdlet to create ESXI VMKernel port for vSphere Replication Traffic to provide greater flexibility:
- Support for Management and VI Workload Domains
- Support for configuring a single site at a time
- Support for handling part failure through re-run
Added `Undo-EsxiVMkernelPort` cmdlet to remove ESXI VMKernel port for vSphere Replication Traffic to provide greater flexibility:
- Support for Management and VI Workload Domains
- Support for configuring a single site at a time
Moved Some …
> feat(pdr): Greater Flexibility for Adding ESXi VMKernel Port for ESXi Hosts

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-EsxiVrmsStaticRoute` cmdlet to provide ESXi static route configuration flexibility
- Added `Undo-EsxiVrmsStaticRoute` cmdlet to provide ESXi static route removal flexibility
- Moved `Undo-EsxiVrmsStaticRoute` cmdlet to Deprecated Functions Region
- Moved `New-vSREsxiStaticRoute` cmdlet to Deprecated Functions Region
Issue Number: Closes #168 
> feat(pdr): Add ESXi Static Route Flexibility

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Added `Request-WsaPasswordExpiration` cmdlet to retrieve the password expiration policy for Workspace ONE Access.
- Added `Request-WsaPasswordComplexity` cmdlet to retrieve the password complexity policy for Workspace ONE Access.
- Added `Request-WsaAccountLockout` cmdlet to retrieve the account lockout policy for Workspace ONE Access.
- Added `Update-WsaPasswordExpiration` cmdlet to update the password expiration policy for Workspace ONE Access.
- Added `Update-WsaPasswordComplexity` cmdlet to update the password …
> feat(iam): workspace one and nsx manager/edge password management

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Added `Get-LocalPasswordComplexity` cmdlet to retrieve the password complexity in `/etc/pam.d/system-password`.
- Added `Set-LocalPasswordComplexity` cmdlet to configure the password complexity in `/etc/pam.d/system-password`.
- Added `Request-VcenterPasswordComplexity` cmdlet to retrieve the password complexity for a vCenter Server.
- Added `Update-VcenterPasswordComplexity` cmdlet to update the password complexity for a vCenter Server.
- Added `Request-NsxtManagerPasswordComplexity` cmdlet to retrieve the password …
> feat(iam): local user password complexity

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Publish-SddcManagerPasswordExpiration` cmdlet to retrieve password expiration policy for SDDC Manager and output the details.
- Added `Publish-SddcManagerPasswordComplexity` cmdlet to retrieve password complexity policy for SDDC Manager and output the details.
- Added `Publish-SddcManagerAccountLockout` cmdlet to retrieve account lockout policy for SDDC Manager and output the details.
- Added `Publish-SsoPasswordExpiration` cmdlet to retrieve password expiration policy for vCenter Single Sign-On and output the …
> feat(iam): moved ppm publish functions from reporting module

- PowerValidatedSolutions.psm1
- Missing NSX Manager Account Lockout missing data in JSON
> fix: nsxmanager account lockout missing

- PowerValidatedSolutions.psm1
- Updated `Get-PasswordPolicyDefaul`t with Workspace ONE Access defaults
> feat: update wsa ppm default values

- PowerValidatedSolutions.psm1
- Modifies `Get-PasswordPolicyConfig` function .
- Adds `checkRange`, `checkEmailString`,  and `Test-PasswordPolicyConfig` functions.
Signed-off-by: Kevin Teng <kteng@vmware.com>
> feat: add `Test-PasswordPolicyConfig`

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `New-vROPSDeployment` license check in vRealize Suite Lifecycle Manager locker.
- Fixed `New-vRADeployment` license check in vRealize Suite Lifecycle Manager locker.
- Enhanced `Export-vRLIJsonSpec` with a new switch to define a custom version of vRealize Log Insight to deploy.
- Enhanced `New-vRLIDeployment` with a new switch to define a custom version of vRealize Log Insight to deploy.
- Enhanced `Export-vROPSJsonSpec` with a new switch to define a custom version of vRealize Operations to deploy.
- Enhanced …
> feat: add support for custom version of vrs

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- **Breaking Change** - Updated `Add-vCenterGlobalPermission` cmdlet to require the `-sddcDomain` parameter to support isolated workload domains.
- **Breaking Change** - Updated `Undo-vCenterGlobalPermission` cmdlet to require the `-sddcDomain` parameter to support isolated workload domains.
- Updated the module version from v2.3.0.1002 to v2.3.0.1003.
- Updated the `CHANGELOG.md`.
Support for isolated workload domains.
**Related to Existing …
> refactor: global permissions for isolated workload domains

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Get-vCenterServerDetail` which had blank SSO Domain for pre-VMware Cloud Foundation 4.5.0.0 release causing `Add-SsoPermission` to fail.
- Updated CHANGELOG.md
- Bumped the version in PowerValidatedSolutions.psd1 from `2.3.0.1005` to `2.3.0.1006`
> fix: address missing sso domain for pre 4.5.0.0 release of VCF

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Initialize-WorkspaceOne` cmdlet to support change in private API for initial configuration of Workspace ONE Access.
N/A
N/A
> fix: update Initialize-WorkspaceOne for updated private api

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-NsxtLogicalRouter` cmdlet to retrieve a list of logical routers.
- Added `Get-NsxtRoutingConfigRedistribution` cmdlet to retrieve information about configured route redistribution for the logical router.
- Added `Get-NsxtRoutingConfigRedistributionRule` cmdlet to retrieve all the route redistribution rules for a logical router.
- Added `Set-NsxtRoutingConfigRedistributionRule` cmdlet to configure the route redistribution rules for a logical router.
- Added `Get-NsxtRoutingConfigRouteMap` cmdlet to retrieve the route map configuration for a logical router.
N/A
N/A
> feat: add nsxt functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-WsaJsonSpec` to support VMware Cloud Foundation v4.5.2 and Workspace ONE Access v3.3.7.
- Enhanced `Export-vROPSJsonSpec` to support VMware Cloud Foundation v4.5.2 and vRealize Operations v8.10.2.
- Enhanced `Export-vRAJsonSpec` to support VMware Cloud Foundation v4.5.2 and vRealize Automation v8.11.2.
- Enhanced `Export-vRLIJsonSpec` to support VMware Cloud Foundation v4.5.2 and vRealize Log Insight v8.10.2.
Closes #316 
N/A
> feat: add support for vcf 452 and vrealize suite

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-NsxtSecurityPolicy` cmdlet to retrieve a list of security policies from NSX.
- Added `Remove-NsxtSecurityPolicy` cmdlet to remove a security policy from NSX.
- Added `Get-NsxtGroup` cmdlet to retrieve a list of groups from NSX.
- Added `Remove-NsxtGroup` cmdlet to remove a group from NSX.
#212 / #213
N/A
> feat: add nsxt security policy and group apis

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Apply a temporary workaround for #265.
Tested functionality for adding new permissions onto a vSphere Namespace.
Closes #265 
None
> fix: issue #265

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Replaced WMI cmdlet usage with CIM cmdlets. Since WMI cmdlets are not available in PowerShell Core, we needed to switch to using CIM cmdlets as they are available in both PowerShell Core and Windows PowerShell.
Tested certificate request and installation process for Supervisor Clusters from end to end, including New-SupervisorClusterCSR, Request-SignedCertificate, and Install-SupervisorClusterCertificate.
Closes #332
> fix: replace wmi cmdlet usage with cim cmdlets

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-ContentLibrary` cmdlet to work on both PowerShell 7 and Windows PowerShell 5.1.
- Updated module version to 2.7.0.1003.
Withe the `-subscriptionUrl` check commented out and run with `-Debug`:
```powershell
PS F:\> Add-ContentLibrary -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re123! -domain sfo-w01 -contentLibraryName Kubernetes1 -subscriptionUrl https://wp-content.vmware.com/v2/latest/lib.json -Debug
DEBUG: 8/30/2023 9:55:35 AM     Get-ContentLibrary
DEBUG: 8/30/2023 9:55:36 AM     Get-Datastore
DEBUG: 8/30/2023 9:55:46 AM     New-ContentLibrary      52723e4d-604b-8b82-28b3-0560363a4416
DEBUG: 8/30/2023 9:55:46 AM     New-ContentLibrary
DEBUG: 8/30/2023 9:55:46 AM     Get-ContentLibrary
Creating …
```
> feat: enhance `Add-ContentLibrary` for powershell 7

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Register-vROPSManagementPack` cmdlet to enable or disable the VMware Cloud Foundation management pack.
Closes #344 
N/A
> feat: activate vcf management pack

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-vROPSVcfCredential` cmdlet to create a VMware Cloud Foundation credential in Aria Operations.
Closes #349 
N/A
> feat: add function to support creating a vcf credential

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-vROPSJsonSpec` to support VMware Cloud Foundation v5.1.0 and vRealize Operations v8.12.1.
- Enhanced `Export-vRAJsonSpec` to support VMware Cloud Foundation v5.1.0 and vRealize Automation v8.13.1.
- Enhanced `Export-vRLIJsonSpec` to support VMware Cloud Foundation v5.1.0 and vRealize Log Insight v8.12.0.
N/A
N/A
> chore: update aria product versions for json specs

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-NsxtLdap` cmdlet to retrieve LDAP identity providers from NSX Manager.
- Added `Remove-NsxtLdap` cmdlet to remove an LDAP identity provider from NSX Manager.
- Enhanced `Install-vRLIPhotonAgent` cmdlet to support VMware Aria Operations for Logs agent configuration.
N/A
N/A
> feat: enhancements for nsx and operations for logs

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleScripts/iam/iamConfigureNsx.ps1
- Fixed an issue with recent change of `Add-vCenterGlobalPermission` where `-localDomain` switch was always set to false
N/A
N/a
> fix: Add-vCenterGlobalPermission

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-vRLIJsonSpec` to support deployment of VMware Aria Operations for Logs OVA using vSphere Content Library.
- Enhanced `New-vRLIDeployment` to support deployment of VMware Aria Operations for Logs OVA using vSphere Content Library.
N/A
N/A
> feat: add support for vrli content library ova deployment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Update `Add-NetworkSegment` to compare segment type w/ `tz_type` property.
- Change `New-NsxtSegment` to dynamically populate TZ path.
- Change `New-NsxtSegment` to use `PATCH` method instead of `PUT`.
- Change `New-NsxtSegement` to look for HTTP 200/204 indicating success.
- Update `Get-NsxtTransportZone` to retrieve values using the proper URI.
Ref #365
Resolved issue adding an overlay-backed NSX segment
Ensured Add-NetworkSegment worked properly with VCF 4.5.2, 5.0.0, and 5.1.0
Closes #365 
None
> fix: error adding an overlay-backed nsx segment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `New-vRSLCMDatacenterVcenter` cmdlet to wait for datacenter to be created before adding the vCenter.
N/A
N/A
> fix: address timing issue adding vcenter to aria suite

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhance `Export-vROPsJsonSpec` JSON spec with new `controllerType` equals NSX_T
- 
NOTE: No update to CHANGELOG.md as this is part of VMware Cloud Foundation 5.1 Support
N/A
N/A
> fix: add aria suite load balancer controller type

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Fixed issue where the embedded Harbor Registry failed to deploy on vSphere 8.0 and up on the following cmdlets:
- `Enable-WMRegistry`
- `Get-WMRegsitry`
- `Remove-WMRegistry`
- `Get-WMRegsitryHealth`
Tested functionality and regression in VCF 4.5.2, 5.0, and 5.1
Closes #369 
None
> fix: error enabling Harbor Registry Service

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-NsxtPrincipalIdentity` cmdlet to get a list of NSX Principal Identities from NSX Manger.
- Added `Set-NsxtPrincipalIdentityCertificate` cmdlet to update the certificate of an NSX Principal Identity in NSX Manager.
- Added `Remove-NsxtPrincipalIdentity` cmdlet to remove an NSX Principal Identity from NSX Manager.
- Added `New-NsxtPrincipalIdentity` cmdlet to create an NSX Principal Identity in NSX Manager.
Closes #386 
N/A
> feat: add nsx principal identity api cmdlets

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-vROPSNsxCredential` cmdlet to create a an NSX credential in VMware Aria Operations.
N/A
N/A
> feat: add nsx credential in aria operations

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Export-vROPSJsonSpec` cmdlet to not populate secondary NTP server address from the Planning and Preparation workbook.
N/A
N/A
> fix: remove secondary ntp from export-vropsjsonspec

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-NsxtIdentitySource` cmdlet to add LDAP/LDAPS Identity Source to NSX Manager.
- Added `Undo-NsxtIdentitySource` cmdlet to remove LDAP/LDAPS Identity Source from NSX Manager.
N/A
N/A
> feat: add nsxt identity source

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Undo-vRLIAuthenticationGroup` cmdlet to remove group assignments from VMware Aria Operations for Logs.
- Enhanced `Get-vRLIGroup` cmdlet to support v2 API for retrieving group membership by authentication provider in VMware Aria Operations for Logs.
- Enhanced `Add-vRLIGroup` cmdlet to support v2 API for adding group membership by authentication provider in VMware Aria Operations for Logs.
- Enhanced `Remove-vRLIGroup` cmdlet to support v2 API for removing group membership by authentication provider in VMware Aria Operations for Logs.
- Enhanced `Add-vRLIAuthenticationGroup` cmdlet to support updated `Add-vRLIGroup` cmdlet usage and Active Directory support.
N/A
N/A
> feat: add changed api support for ops for logs group management

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Add-vRLIAuthenticationWSA` cmdlet description and synopsis which was incorrect.
- Added `Set-vRLIAuthenticationAD` cmdlet to configure Active Directory as an authentication provider in VMware Aria Operations for Logs.
- Added `Remove-vRLIAuthenticationAD` cmdlet to disable Active Directory as an authentication provider in VMware Aria Operations for Logs.
- Added `Add-vRLIAuthenticationAD` cmdlet to enable and configure Active Directory as an authentication provider in VMware Aria Operations for Logs.
- Added `Undo-vRLIAuthenticationAD` cmdlet to disable Active Directory as an authentication provider in VMware Aria Operations for Logs.
N/A
N/A
> feat: add support for ad authentication in ops for logs

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-NsxtLdapRole` cmdlet to assign an LDAP user or group role-based access control in NSX Manager.
- Added `Undo-NsxtLdapRole` cmdlet to remove an LDAP user or group role-based access control from NSX Manager.
`Add-NsxtLdapRole`
`Undo-NsxtLdapRole` 
N/A
N/A
> feat: add ldap support for nsx manager

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Undo-vRLIAuthenticationWSA` cmdlet to support disable Workspace ONE Access integration with VMware Aria Operations for Logs.
N/A
N/A
> feat: add undo-vrliauthenticationwsa

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-vRSLCMLoadbalancer` cmdlet to support retrieving a list of load balancers configure in VMware Aria Suite Lifecycle.
- Added `New-vRSLCMLoadbalancer` cmdlet to support adding a new load balancer to VMware Aria Suite Lifecycle.
- Added `Remove-vRSLCMLoadbalancer` cmdlet to support removing a load balancer from VMware Aria Suite Lifecycle.
- Enhanced `New-WSADeployment` cmdlet to check for existence of the a load balancer in VMware Aria Suite Lifecycle and if missing create it.
- Enhanced `New-vROPSDeployment` cmdlet to check for existence of the a load balancer in VMware Aria Suite Lifecycle and if missing create it.
- Enhanced `New-vRADeployment` cmdlet to check for existence of the a load balancer in VMware Aria Suite Lifecycle and if missing create it.
N/A …
> feat: add support for aria suite lifecycle load balancer

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Export-IamJsonSpec` for NSX identity provider configuration.
- Updated `Invoke-IamDeployment` to support new NSX identity provider json inputs.
- Updated `Invoke-UndoIamDeployment` to support new NSX identity provider json inputs.
- Added `Get-NsxtLdapStatus` cmdlet to retrieve the configuration status of an identity source in NSX.
- Fixed `Add-NsxtLdapRole` cmdlet which was passing the Workload Domain rather than the identity source domain when assigning groups and users.
- Enhanced `Add-NsxtIdentitySource` cmdlet to use `Get-NsxtLdapStatus` and check if the identity source connection is operational.
- Enhanced `Undo-SddcManagerRole` cmdlet for better error handling and message output.
N/A
N/A
> feat: enhanced error checking for iam deployments

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-vRSLCMMyVMwareAccount` cmdlet to add a Customer Connect Account to VMware Aria Suite Lifecycle.
- Added `Undo-vRSLCMMyVMwareAccount` cmdlet to remove a Customer Connect Account to VMware Aria Suite Lifecycle.
N/A
N/A
> feat: add support for customer connect account

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Invoke-UndoPcaDeployment` cmldet to perform an end-to-end removal of Private Cloud Automation.
- Added `Export-GlobalWsaJsonSpec` cmdlet to generate a JSON specification file for Workspace ONE Access.
- Added `Invoke-GlobalWsaDeployment` cmdlet to perform an end-to-end install of Workspace ONE Access.
- Added `Invoke-UndoGlobalWsaDeployment` cmdlet to perform an end-to-end removal of Workspace ONE Access.
- Added `Undo-WSADeployment` cmdlet to remove Workspace ONE Access from VMware Aria Suite Lifecycle.
- Added `Undo-AslcmDeployment` cmdlet to remove VMware Aria Suite Lifecycle from SDDC Manager.
- Added `Export-AslcmJsonSpec` cmdlet to generate a JSON specification file for VMware Aria Suite Lifecycle.
- Added `Invoke-AslcmDeployment` cmdlet to perform an end-to-end install of …
> feat: add oneclick for global wsa and aslcm

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-NsxtPrincipalIdentity` cmdlet to add a certificate based principal identity to NSX Manager.
- Added `Undo-NsxtPrincipalIdentity` cmdlet to remove a certificate based principal identity from NSX Manager.
N/A
N/A
> feat: add/remove nsxt principal identity

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Remove-vRLIContentPack` cmdlet to support the removal of a content pack from VMware Aria Operations for Logs.
- Added `Uninstall-vRLIContentPack` cmdlet to remove a content pack from VMware Aria Operations for Logs.
N/A
N/A
> feat: add content pack removal

- LICENSE
- Makefile
- NOTICE
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- README.md
- SampleScripts/dri/driConfigureSupervisorCluster.ps1
- SampleScripts/dri/driDeployTanzuCluster.ps1
- SampleScripts/dri/driUndoDeployment.ps1
- SampleScripts/iam/iamSolutionInteroperability.ps1
- SampleScripts/ila/ilaSolutionInteroperability.ps1
- SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
- SampleScripts/iom/iomSolutionInteroperability.ps1
Updates the copyright to 2023-2024.
> chore: update copyright

- docs/requirements.txt
- docs/snippets/install-module.ps1
- mkdocs.yml
- Updates installation documentation for the v2.8.0 release.
- Updates the MkDocs plugin requirements.
- Updates the MkDocs configuration to include missing functions.
```console
power-validated-solutions-for-cloud-foundation on  docs/update-documentation 
➜ make docs-install   
pip install mkdocs-material
Collecting mkdocs-material
Using cached mkdocs_material-9.5.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: babel~=2.10 in /usr/local/lib/python3.11/site-packages (from mkdocs-material) (2.12.1)
Requirement already satisfied: colorama~=0.4 in /usr/local/lib/python3.11/site-packages (from mkdocs-material) (0.4.6)
Requirement already satisfied: jinja2~=3.0 in /usr/local/lib/python3.11/site-packages (from mkdocs-material) (3.1.2)
Requirement already …
```
> docs: documentation updates

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-vRSLCMUpgradeStatus` cmdlet to retrieve the status of an upgrade of VMware Aria Suite Lifecycle.
- Added `Start-vRSLCMUpgrade` cmdlet to start check, prepare, pre-validate and upgrade operations on VMware Aria Suite Lifecycle.
- Renamed Aslcm functions to vRSLCM
N/A
N/A
> feat: add supporting functions for vrslcm upgrade

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations/Add-vROPSAdapterVcf.md
- docs/documentation/functions/solutions/iom/index.md
- mkdocs.yml
- Added `Add-vROPSAdapterVcf` cmdlet to support creating the VMware Cloud Foundation adapter in VMware Aria Operations.
- Enhanced `Invoke-IomDeployment` cmdlet to include `Add-vROPSAdapterVcf` for creating the VMware Cloud Foundation adapter in VMware Aria Operations.
N/A
N/A
> feat: add support for creating vcf adapter in aria operations

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/cbr/Export-CbrJsonSpec.md
- docs/documentation/functions/solutions/cbr/Invoke-CbrDeployment.md
- docs/documentation/functions/solutions/cbr/Invoke-UndoCbrDeployment.md
- docs/documentation/functions/solutions/cbr/index.md
- mkdocs.yml
- Added `Export-CbrJsonSpec` cmdlet to generate a JSON specification file for Cloud-Based Ransomware Recovery.
- Added `Invoke-CbrDeployment` cmdlet to perform an end-to-end deployment of Cloud-Based Ransomware Recovery.
- Added `Invoke-UndoCbrDeployment` cmdlet to perform removal of Cloud-Based Ransomware Recovery.
- Added `messageHandler` cmdlet an internal function to handle multiple lines of message output for end-to-end deployments.
- Added documentation for Cloud-Based Ransomware Recovery OneClick cmdlets.
- Updated `Invoke-CbrDeployment` cmdlet to use `messageHandler`.
- Updated `Invoke-UndoCbrDeployment` cmdlet to use `messageHandler`.
N/A
N/A
> feat: add oneclick for cbr

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Set-vRSLCMDnsConfig` cmdlet to perform a check to see if the configuration has already been carried out.
- Enhanced `Set-WorkspaceOneDnsConfig` cmdlet to check if the configuration has already been carried out before attempting to shutdown Workspace ONE Access.
- Enhnaced `Set-vROPSDnsConfig` cmdlet to check if the configuration has already been carried out.
- Enhanced `Add-vROPSNtpServer` cmdlet to check if the configuration has already been carried out.
- Enahnced `Set-vRADnsConfig` cmdlet to check if the configuration has already been carried out.
- Enhanced `Set-vRANtpConfig` cmdlet to check if the configuration has already been carried out.
N/A
N/A
> feat: improve dns changes

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-DriDeployment` cmdlet to handle message output for error during execution of `Add-StoragePolicy`.
Closes #537 
N/A
> fix: address error output for storage policy creation

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Get-vRLIRole` cmdlet to ensure it returns data correctly from the API.
Closes #533 
N/A
> fix: Get-vRLIRole not returning data correctly

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Export-WsaJsonSpec` with support for VMware Cloud Foundation 5.1.1.
- Fixed `Export-vROPSJsonSpec` type for support for VMware Cloud Foundation 5.1.1.
Closes #544 
N/A
> feat: update wsa version

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-PcaDeployment` cmdlet where the `Add-NsxtVidmRole` was used instead of `Add-NsxtLdapRole`.
N/A
N/A
> fix: udpate step to use Add-NsxtLdapRole

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-PcaDeployment` cmdlet where the -vraUser value in `New-vRACloudAccount` was incorrect.
N/A
N/A
> fix: wrong -vraUser value in New-vRACloudAccount

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-DriDeployment` cmdlet where `Add-Namespace` -server value was not pulling from the JSON file.
Closes #551 
N/A
> fix: incorrect input for add-namespace

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-IlaDeployment` cmdlet to force GitHub Token from JSON to a string value.
- Fixed `Add-IdentitySource` cmdlet to include -Server parameter to support isolated workload domains.
Closes #550 
N/A
> fix: enable vrli content pack

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/nsx/Add-NsxtIdentitySource.md
- Fixed `Test-ADAuthentication` cmdlet to pass failure message as an output rather than error message so it can be evaluated.
- Enhanced `Add-NsxtIdentitySource` cmdlet to verify the Active Directory credentials are valid.
Closes #558 
N/A
> feat: enhance add-nsxtidentitysourc to validate ad credentials

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-PcaDeployment` cmdlet where it was throwing errors when creating a Cluster Group when Standard Workspace ONE Access is deployed.
- Enhanced `Invoke-UndoPcaDeployment` cmdlet to remove the VM folder for Private Cloud Automation.
- Enhanced `Invoke-HrmDeployment` cmdlet to set the $failureDetected variable to false before starting the deployment.
- 
N/A
N/A
> fix: address end-to-end deployement issues

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Add-vRSLCMGroup.md
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Add-vRSLCMGroupRole.md
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMGroup.md
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMRole.md
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Remove-vRSLCMGroup.md
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Undo-vRSLCMGroupRole.md
- mkdocs.yml
- Added `Get-vRSLCMRole` cmdlet to retrieve a list of VMware Aria Suite Lifecycle roles.
- Added `Get-vRSLCMGroup` cmdlet to retrieve a list of VMware Aria Suite Lifecycle group assignments.
- Added `Add-vRSLCMGroup` cmdlet to add a group to a roles in VMware Aria Suite Lifecycle.
- Added `Remove-vRSLCMGroup` cmdlet to remove the role assignments for a group in VMware Aria Suite Lifecycle.
- Added `Add-vRLCMSGroupRole` cmdlet to add roles to groups in VMware Aria Suite Lifecycle.
- Added `Undo-vRLCMSGroupRole` cmdlet to remove group roles in VMWare Aria Suite Lifecycle.
- Enhanced `Invoke-GlobalWsaDeployment` cmdlet to use `Add-vRLCMSGroupRole` to configure VMware Aria Suite Lifecycle roles.
Closes #563 
N/A
> feat: add support for vrslcm role assignment

- .vscode/settings.json
- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Enable-Registry` cmdlet to handle clean exit of function when running vSphere 8.0.
- Enhanced `Add-Namespace` cmdlet to handle expected missing object and not throw an error.
Closes #580 
N/A
> fix: dri oneclick exiting

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Backup-VMOvfProperties` cmdlet to check for the existing of each VMware Aria component and skip backing up the OVF settings if not present.
Closes #591 
N/A
> feat: enhance backup-vmovfproperties to skip missing aria products

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/certificates/Invoke-GeneratePKCS12.md
- docs/documentation/functions/site-recovery-manager/Install-VamiCertificate.md
- docs/documentation/functions/site-recovery-manager/Request-VamiPKCS12Certificate.md
- docs/documentation/functions/site-recovery-manager/Test-SrmAuthenticationREST.md
- docs/documentation/functions/site-recovery-manager/Test-SrmConnection.md
- docs/documentation/functions/site-recovery-manager/Test-SrmSdkAuthentication.md
- docs/documentation/functions/solutions/pdr/index.md
- docs/documentation/functions/vsphere-replication/Install-VamiCertificate.md
- docs/documentation/functions/vsphere-replication/Request-VamiPKCS12Certificate.md
- docs/documentation/functions/vsphere-tanzu/Install-TanzuSignedCertificate.md
- mkdocs.yml
- Added `Install-TanzuSignedCertificate` cmdlet to request and install a signed certificate for the Tanzu Supervisor Cluster.
- Added `Test-SrmSdkAuthentication` cmdlet to verify authentication using the PowerCLI Sdk module for Site Recovery Manager.
- Added `Invoke-GeneratePKCS12` cmdlet to generate a PKCS12 file (.pfx) to support certificate replacement of vSphere Replication and Site Recovery Manager.
- Added `Request-VamiPKCS12Certificate` cmdlet to generate Private Key (.key), Signed Certificate (.crt) and PKCS12 file (.pfx) files for vSphere Replication and Site Recovery Manager.
- Enhanced `Undo-RecoveryPlan` cmdlet to consume the Site Recovery Manager PowerCLI cmdlets and improve error handling and message output.
- Enhanced `Undo-ProtectionGroup` cmdlet to consume the Site …
> feat: certificate management

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Add-SrmLicenseKey` cmdlet which was failing due to incorrect placement of `Disconnect-SrmServer` command.
- Fixed `Undo-SrmLicenseKey` cmdlet which was not issuing a `Disconnect-SrmServer` command.
Closes #600 
N/A
> fix: Add-SrmLicenseKey failure

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMDatacenter.md
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Invoke-vRSLCMUpgrade.md
- docs/documentation/functions/solutions/wsa/Invoke-GlobalWsaDeployment.md
- mkdocs.yml
- Fixed `Invoke-GlobalWsaDeployment` cmdlet where an error is thrown when creating the Datacenter and vCenter Server objects for Cross-Instance.
N/A
N/A
> fix: aria suite datacenter creation error

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Get-vRAvRLIConfig` cmdlet where is failed due to an OpenSSL error being returned with the data.
Closes #605
> fix: Get-vRAvRLIConfig cmdlet failing due to warning in the output

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Undo-AriaNetworksDeployment.md
- docs/documentation/functions/solutions/inv/Invoke-InvDeployment.md
- docs/documentation/functions/solutions/inv/Invoke-UndoInvDeployment.md
- docs/documentation/functions/solutions/inv/index.md
- mkdocs.yml
- Added `Invoke-InvDeployment` cmdlet to perform an end-to-end deployment of Intelligent Network Visibility.
- Added `Invoke-UndoInvDeployment` cmdlet to perform removal of Intelligent Network Visibility.
- Updated Documentation.
N/A
N/A
> feat: add end-to-end deployment for inv

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Export-InvJsonSpec` not adding gateway which is needed for the depoyment.
- Fixed `Export-InvJsonSpec` not adding netmask which is needed for the deployment.
- Fixed `Export-AriaNetworksJsonSpec` using wrong alias for the root user.
- Fixed `Export-AriaNetworksJsonSpec` using wrong variable if -customVersion passed.
- Fixed `Export-AriaNetworksJsonSpec` library items as looking for .ova which is incorrect.
- Fixed `Export-AriaNetworksJsonSpec` wrong values being pulled from the JSON for Platform node.
- Fixed `Export-AriaNetworksJsonSpec` type in the collector hostname value.
- Fixed `New-AriaNetworksDeployment` wrong syntax used for calling `Export-AriaNetworksJsonSpec` and function name.
- Enhanced `Invoke-InvDeployment` to include `New-AriaNetworksDeployment`. …
> fix: testing aria networks deployment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-VrmsNetworkAdapter` cmdlet to set the eth1 interface status to up for the vSphere Replication appliance.
N/A
> feat: enable eth1 for vsphere replication

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-PdrDeployment` where the incorrect gateway was being passed to the `Add-EsxiVrmsStaticRoute` cmdlet.
- Enhanced `Invoke-UndoPdrDeployment` cmdlet to check for the existence of VMware Aria Automation and VMware Aria Operations.
- 
Closes #621
> fix: replication issues for pdr

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Test-IamPrerequisite` to include the domain when checking services accounts.
- Updated `Test-IlaPrerequisite` to include the domain when checking services accounts.
- Updated `Test-IomPrerequisite` to include the domain when checking services accounts.
- Updated `Test-InvPrerequisite` to include the domain when checking services accounts.
- Updated `Test-PcaPrerequisite` to include the domain when checking services accounts.
- Updated `Test-HrmPrerequisite` to include the domain when checking services accounts.
- Updated `Test-CbwPrerequisite` to include the domain when checking services accounts.
- Updated `Test-CcmPrerequisite` to include the domain when checking services accounts.
- Updated `Invoke-vRSLCMDeployment` to wait 30 seconds after mounting the CD-ROM before …
> fix: service account checks for multiple domains

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/vsphere-replication/Add-VrmsReplication.md
- docs/documentation/functions/vsphere-replication/Add-vSphereReplication.md
- Enhanced  cmdlet by adding a parameter for the datastore t`Add-VrmsReplication`o replicate the virtual machine to.
- Enhanced `Add-vSphereReplication` cmdlet to obtain the primary datastore in the recovery site and pass it to the `Add-VrmsReplication` cmdlet.
Closes #633
> fix: add-vrmsreplication to pass datastore name

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-IamDeployment` and `Invoke-UndoIamDeployment` where it was not discovering the NSX service accounts correctly.
> fix: incorrect service accounts discovered for no access

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-IlaDeployment` cmdlet to configure NSX Syslog servers in the correct order after connecting VI Workload Domains.
N/A
> fix: order of nsx syslog configuration

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-GlobalWsaDeployment` cmdlet to check for stretched cluster to be enabled and configure Anti-Affinity rule.
N/A
> fix: anti-affinity for az and workspace one access

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-PdrJsonSpec` cmdlet to include additional details for Anti-Affinity rule and Startup Group configuration in the recovery instance.
- Enhanced `Invoke-PdrDeployment` cmdlet to perform recovery instance configuration tasks.
- Enhanced `Invoke-UndoPdrDeployment` cmdlet to perform the removal of recovery instance configuration tasks.
N/A
> feat: add recovery site configuration to pdr end-to-end

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Updates the content pack install/update to compress the payload with gzip.
```powershell
PS C:\Users\Administrator> Enable-vRLIContentPack -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -token $mytoken -contentPack WSA
WARNING: Installing Content Pack (VMware Workspace ONE Access v2.2) to VMware Aria Operations for Logs (sfo-vrli01.sfo.rainpole.io), already exists: SKIPPED
PS C:\Users\Administrator> Remove-vRLIContentPack -namespace 'com.vmware.vidm'
PS C:\Users\Administrator> Enable-vRLIContentPack -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -token $mytoken -contentPack WSA
Installing content pack (VMware Workspace ONE Access v2.2) to VMware Aria Operations for Logs (sfo-vrli01.sfo.rainpole.io): …
```
> refactor: compress content pack

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced all `Export-???JsonSpec` cmdlets to check for 'N/A', 'n/a' and '#VALUE' values extracted from the Planning and Preparation Workbook and warn.
Closes #692
> feat: add additional value checks on pnp extract

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Udpated `Export-DriJsonSpec` with new named cell following changes to the PnP.
> fix: changed named cell for supervisor cluster

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-DriJsonSpec` cmdlet to define the path to the Kubectl utility.
- Enhanced `Start-DriMenu` cmdlet to use the new JSON value for the path to the Kubectl utility.
Closes #705
> fix: kubectl path in JSON

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/nsx/Get-NsxtGlobalManagerConfig.md
- Enhanced `Get-NsxtGlobalManagerConfig` cmdlet to retrieve global manager config from the local manager.
- Updated `Get-NsxtGlobalManagerConfig` documentation.
- Fixed `Test-PdrPrerequisite` cmdlet where DNS Servers were not extracted correctly.
- Enhanced `Test-PdrPrerequisite` cmdlet to verify that NSX Federation is configured in the environment.
- 
Closes #708
> feat: pdr prerequisite check for nsx federation

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Export-HrmJsonSpec` cmdlet to add the DNS servers with a "," in place of a space for consistency with other JSON specs.
- Fixed `Export-PdrJsonSpec` cmdlet to add the DNS servers with a "," in place of a space for consistency with other JSON specs.
- Fixed `Test-PdrPrerequisite` cmdlet to split the DNS servers with a "," in place of a space for consistency with other test pre req functions.
Closes #750
> fix: dns prereqs

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-CbrJsonSpec` cmdlet to export the DRaaS Connector hostname and FQDN.
- Fixed `Export-CbrJsonSpec` cmdlet where is was exporting HCX Connector details incorrectly.
- Fixed `Test-CbrPrerequisite` cmdlet to check for the DRaaS Connector FQDNs in DNS.
> fix: address dns check issue with cbr

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/active-directory/Get-ADPrincipalGuid.md
- docs/documentation/functions/workspace-one-access/Add-WorkspaceOneDirectory.md
- docs/documentation/functions/workspace-one-access/Add-WorkspaceOneDirectoryGroup.md
- docs/documentation/functions/workspace-one-access/Undo-WorkspaceOneDirectoryGroup.md
- Enhanced `Add-WorkspaceOneDirectory` cmdlet with -domainController parameter.
- Enhanced `Add-WorkspaceOneDirectoryGroup` cmdlet with -domainController parameter.
- Enhanced `Undo-WorkspaceOneDirectoryGroup` cmdlet with -domainController parameter.
- Enhanced `Get-ADPrincipalGuid` cmdlet with -domainController parameter.
- Enhanced `Invoke-IomDeployment` cmdlet with -domainController parameter for `Add-WorkspaceOneDirectoryGroup`.
- Enhnced `Invoke-PcaDeployment` cmdlet with -domainController parameter for `Add-WorkspaceOneDirectoryGroup`.
- Enhanced `Invoke-GlobalWsaDeployment` cmdlet with -domainController parameter for `Add-WorkspaceOneDirectory`.
- Updated documentation.
> feat: enhanced ad group sync in wsa

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Based on the way the function is authored, even though both -registerYaml and -configureYaml are marked as optional, the function actually requires both to work. And, if one is empty, then the GetBytes method throws an exception.
This pull request includes updates to the `PowerValidatedSolutions` module, focusing on enhancing the `Add-SupervisorService` function and updating the module version.
Enhancements to `Add-SupervisorService` function:
* Changed the `registerYaml` parameter to mandatory, ensuring that it is always provided when the function is called.
* Removed code that set default values for `registerYaml` and `configureYaml` parameters if they were not provided.
* Added validation to check if the `registerYaml` file exists before proceeding with the registration process, and …
> fix: GetBytes exception

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/vsphere-tanzu/Enable-SupervisorCluster.md
Adds an option in `Enable-SupervisorCluster` to set the name of the supervisor cluster instead of inheriting it from the vSphere cluster name (default).
Closes #764
> feat: set supervisor cluster name
