- SampleScripts/iam/iamConfigureNsx.ps1
- SampleScripts/iam/iamConfigureVsphere.ps1
- SampleScripts/iam/iamConfigureWorkspaceOne.ps1
- SampleScripts/ila/ilaConfigureVrealizeLogInsight.ps1
- SampleScripts/ila/ilaDeployVrealizeLogInsight.ps1
- SampleScripts/iom/iomConfigureVrealizeOperations.ps1
- SampleScripts/iom/iomDeployVrealizeOperations.ps1
Updates to Sample Scripts to Support VMware Cloud Foundation 4.4 Planning and Preparation Workbook
- [ X ] This is an enhancement or feature.
Signed-off-by: Gary Blake [gblake@vmware.com](mailto:gblake@vmware.com)
> Updated Sample Scripts to Support VCF 4.4 PnP Workbook

- PowerValidatedSolutions.psm1
Added support for different JSON payloads across vROPS versions.
Closes #10 
> Fix Add-vROPSAdapterSddcHealth

- PowerValidatedSolutions.psm1
Adds two functions
- Test-vROPsAdapterStatus,
- Test-vROPsAdapterStatusByType
#22
Signed-off-by: Lakshmanan Shanmugam <lshanmugam@vmware.com>
Closes : #22 
> feat: Add vROPS adapter verification

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhancement to Request-CSPToken
- Added Get-vROVersion with support for standalone, embedded and extensibility instances
- Added Get-CEPWorkflow to retrieve Workflows from CEP vRO Instance
- Added Invoke-CEPWorkflow to start a Workflow on CEP vRO Instance
- Added Get-CEPWorkflowExecution to get the Workflow Execution ID
- Added Get-CEPWorkflowExecutionState to get the Workflow Execution State
- Added Add-CEPTrustedCertificate to add a trusted cert to vRO
> Add Cloud Extensibility Proxy (CEP) and vRealize Orchestrator Functions

- PowerValidatedSolutions.psm1
Fixes issue in GH-25.
Closes #25 
> fix: gh-25

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Added #Region and #EndRegion to each code block to provide easier navigation of the code.
> Added Region Blocks to Code for Easier Navigation

- PowerValidatedSolutions.psm1
Added function :  `Update-vROPSvRAAdapterCredential `
Updated function : `Undo-vROPSCredential `
Signed-off-by: Lakshmanan Shanmugam <lshanmugam@vmware.com>
Closes : #27 
> feat: Add support to update the vRealize Automation Integration credential in vRealize Operations Manager

- PowerValidatedSolutions.psm1
Add cmdlet
- `Set-EsxiPasswordExpirationPeriod`
This cmdlet is use to set the password expiration period on an ESXi host in number of days.
Sign-off-by: Kevin Teng <kteng@vmware.com>
Closes #34 
> feat: Add support to configure the ESXi password expiration policy

- PowerValidatedSolutions.psm1
Enhances `Update-vRACloudAccountZone` and `Update-vRACloudZone` cmdlets to support placement policy for Cloud Zones in vRealize Automation
Supported placement policies: 
- ADVANCED
- DEFAULT 
- SPREAD 
- BINPACK
Adds new `Get-vRAAPIVersion` and `Get-vRAIntegrationDetail` cmdlets to support the same.
Signed-off-by: Lakshmanan Shanmugam <lshanmugam@vmware.com>
Issue Number: 
Closes : #39 
> feat: Add support to update placement policy for cloud zones in vRealize Automation

- PowerValidatedSolutions.psm1
The following functions are included in the module and exported; however, these are not used in the module. 
These are however included in the PowerVCF module where they are not exported and are used extensively.
- `checkVCFToken`
- `Get-JWTDetail`
Minor `region` format correction.
Resolves: #59
> fix: Remove duplicated, exported functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Renamed `Resolve-PSModule` to `Confirm-PSModule`
- Added Export-ModuleMember to Enable CLI Execution.
- Updated Synopsis, Description, Example
- Minor Tweaks to Output
- Performed Testing in Local Lab
Issue Number: Closes #80 
> feat: enhance `Confirm-PSModule`

- PowerValidatedSolutions.psm1
- Update formatting of IAM functions, help with collapsing of code
> chore: review and update formatting for iam functions

- PowerValidatedSolutions.psm1
- Update formatting across DRI functions
> chore: review and update formatting for pdr functions

- PowerValidatedSolutions.psm1
- Updated Formatting for IOM Functions
> chore: review and update formatting for iom functions

- PowerValidatedSolutions.psm1
- Updated formatting of PCA Functions
> chore: review and update formatting for pca functions

- PowerValidatedSolutions.psm1
Update formatting for Shared Functions 
> chore: review and update formatting for shared functions

- PowerValidatedSolutions.psm1
- Refactors `Add-ResoucePool` to use generic `Test-` functions.
- Refactors `Undo-ResoucePool` to use generic `Test-` functions.
Issue Number: Closes #90
> refactor: resource-pool functions

- PowerValidatedSolutions.psm1
Adds support for integrating vRealize Automation with vRealize Operations Manager
Adds the following cmdlets to support the same.
- `New-vRAvROPSIntegrationItem`
- `Add-vRAIntegrationItem`
- `Test-vRAIntegrationItem`
- `Remove-vRAIntegrationItem`
- `Undo-vRAvROPsIntegrationItem`
Signed-off-by: Lakshmanan Shanmugam <lshanmugam@vmware.com>
Closes #44  
> feat: add vrops integration in vra

- PowerValidatedSolutions.psm1
Updated Enable-vROPSManagementPack to support the installation of additional management packs:
- Site Recovery Manager
- vSphere Replication
Issue Number: Closes #67 
> enhance: add support for srm/vr management packs

- PowerValidatedSolutions.psd1
- Removes spaces - needed for v1.8.0 release.
- Add `VMwareValidatedSolutions` and `VMwareCloudFoundation`
> fix: update module metadata

- PowerValidatedSolutions.psm1
Correct syntax on `Set-vRAvRLIConfig ` blocking module import for v1.8.0.
> fix: correct blocking syntax on `Set-vRAvRLIConfig `

- PowerValidatedSolutions.psm1
Adds support for installing the vRealize Orchestrator content pack for vRealize Log Insight from the in-product marketplace, which is hosted on GitHub. This is an online mode online as see in [Install the vRealize Orchestrator Content Pack for vRealize Log Insight](https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-private-cloud-automation-v1/GUID-2F3B32B8-7F20-4B2E-AAE5-9445DC807906.html).
> **Note**
>
> [Install the vRealize Orchestrator Content Pack for vRealize Log …
> feat: install content pack for vro

- PowerValidatedSolutions.psm1
Addresses #101
Signed-off-by: Antony Stefanov <astefanov@vmware.com>
Closes: #101
> fix: address gh-101

- PowerValidatedSolutions.psm1
Updates the `Get-vRAvRLIConfig` cmdlet to convert the output from JSON.
> fix:  get-vravrliconfig convertfrom-json

- PowerValidatedSolutions.psm1
Replaces the use of a term that may be considered insensitive as identified by linter.
> fix: inclusive language

- CODEOWNERS
Adds `CODEOWNERS` to auto-assign pull request reviews to `@vmware-samples/power-validated-solutions-for-cloud-foundation-maintainers`.
Reference: [About CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners).
> chore(repo): add `CODEOWNERS`

- .github/ISSUE_TEMPLATE/docs.yml
Adds YAML-based template for documentation related issues.
- [] No, there are no breaking changes.
> chore(repo): add docs issue template

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Add -standard parameter to `Export-WsaJsonSpec`
- Add -standard parameter to `New-WSADeployment`
Enhancements to cmdlet supporting the deployment of Workspace ONE Access via vRealize Suite Lifecycle Manager
Issue Number: Closes #118 
> feat: support standard Workspace ONE Access instance

- .github/workflows/issues.yml
Comments out the `first-interaction` step due to a known issue that has been seen in `actions/first-interaction#v1`.
Reference: https://github.com/actions/first-interaction/issues/101
Please describe: `ci`
> ci(issues): disable workflow step

- PowerValidatedSolutions.psm1
Adds the following functions to support the import of a user account from the Workspace ONE Access (`vIDMAuthSource`) authentication source.
User Functions:
- `Import-vROPSUserAccount`
Helper Functions:
- `Get-vROPSUserAccount`
- `Add-vROPSUserAccount`
- `Remove-vROPSUserAccount`
- `Search-vROPSUserAccount`
- `Update-vROPSUserAccount` - _to be used in updates for adapter access._
Issue Number: …
> feat: import vrops user from authsource

- PowerValidatedSolutions.psd1
> chore: bump module version to 1.9.0.1001

- SampleScripts/iam/iamConfigureNsx.ps1
- SampleScripts/iam/iamConfigureVsphere.ps1
- SampleScripts/iam/iamConfigureWorkspaceOne.ps1
- SampleScripts/iam/iamUndoDeployment.ps1
Updated SampleScripts for IAM to Support VCF 4.5
- `./SampleScripts/iam/iamConfigureVsphere.ps1`
- `./SampleScripts/iam/iamConfigureWorkspaceOne.ps1`
-` ./SampleScripts/iam/iamConfigureNsx.ps1`
- `./SampleScripts/iam/iamUndoDeployment.ps1`
Issue Number: Closes #125 
> chore: update IAM SampleScripts to support VCF 4.5 PnP workbook

- CHANGELOG.md
- SampleScripts/dri/driConfigureSupervisorCluster.ps1
- SampleScripts/dri/driDeployTanzuCluster.ps1
- SampleScripts/dri/driUndoDeployment.ps1
- Updated `CHANGELOG`, including iam Sample Script Updates
- `/SampleScripts/dri/driConfigurSupervisorCluster.ps1`
- `/SampleScripts/dri/driDeployTanzuCluster.ps1`
- `/SampleScripts/dri/driUndoDeployment.ps1`
Updates DRI Sample Scripts for VCF 4.5 Support
Issue Number: Closes #127 
> feat: Update DRI Sample Scripts for VCF 4.5 Support

- CHANGELOG.md
- SampleScripts/iom/iomConfigureVrealizeOperations.ps1
- SampleScripts/iom/iomDeployVrealizeOperations.ps1
- Updated `CHANGELOG`
- Updated `/SampleScripts/iom/iomConfigureVrealizeOperations.ps1`
- Updated `/SampleScripts/iom/iomDeployVrealizeOperations.ps1`
Issue Number: Close #130 
> feat: update iom sample scripts

- CHANGELOG.md
- PowerValidatedSolutions.psm1
Add support to update content packs in vRealize Log Insight from the in-product content pack marketplace.
- Updates `Install-vRLIContentPack`
- Updates `Get-vRLIMarketplaceMetadata`
- Adds `Update-vRLIContentPack`
- Refactors `Enable-vRLIContentPack` to support a broader set of content packs.
Closes: #56
> feat(ila): update content pack

- PowerValidatedSolutions.psm1
Updates `Get-vRLILogForwarder` function to return the correct response. 
Noticed the issue whilst working on function for configuring both log forwarder filters and tags.
> fix(ila): get log forwarder by id

- PowerValidatedSolutions.psm1
- Adds `Update-vRLILogForwarder` to be used later for tags and filters.
- Updates `-name` argument in `Add-vRLILogForwarder` examples.
Issue Number: #55 
> feat(ila): update log forwarder

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleScripts/ila/ilaConfigureVrealizeLogInsight.ps1
- SampleScripts/ila/ilaDeployVrealizeLogInsight.ps1
- SampleScripts/iom/iomDeployVrealizeOperations.ps1
- Update VCF 4.5 Versions of vRealize Suite to JSON Specs
- Fixed Issue Calling `Add-vRLISmtpConfiguration`
- Added check for missing Archive Details to skip retention configuration in `ilaDeployVrealizeLogInsight.ps1`
- Added check for node count on WSA to `ilaConfigureVrealizeLogInsight.ps1`
- Added `-nested` parameter to vROPS JSON and Deployment for minimal installs
- Added `-nested` parameter to `Export-vROPSJsonSpec` and `New-vROPSDeployment`
- Added `-nested` parameter to `iomDeployVrealizeOperations.ps1` …
> feat: update and validation for VCF 4.5 and sample scripts

- CHANGELOG.md
- SampleScripts/pca/pcaDeployVrealizeAutomation.ps1
Adding Sample Script for Private Cloud Automation
> feat: add sample script for private cloud automation solution deployment

- PowerValidatedSolutions.psm1
- SampleScripts/dri/driConfigureSupervisorCluster.ps1
- Fix Typo in Add-`TanzuKubernetesCluster`
- Fxes issues with the Sample Script `driConfigureSupervisorCluster.ps1`
> fix(dri): address issues in samples

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-StorageFolder` to create Storage Folders
- Updated `Undo-VMFolder` to show removing a storage folder
- Minor adjustments to `CHANGELOG.md` for consistency
- Bumped ModuleVersion to `1.9.0.1008`
> feat: Add a Function to Create a Storage Folder

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added a check for existing cluster in `Enable-SupervisorCluster`
> feat: add check for existing supervisor cluster

- PowerValidatedSolutions.psm1
- SampleScripts/pca/pcaDeployVrealizeAutomation.ps1
- Added Assign Organization and Service Roles
- Added Upfront Checks on vSphere Role Templates
- Fixed issue with root certificate path
- Fixed $nsxEdgeVMFolder population from Workbook
> Add Missing Items to PCA Sample Script

- PowerValidatedSolutions.psm1
- Refactor to use of Test-VCFConnection / Test-VCFAuthentication
- Refactor to use use of Test-VsphereConnection / Test-VsphereAuthentication
- Improvements in message output
- Refactored the handling of obtaining $dnsServer
- Refactored the handling of obtaining $ntpServer
- Added a -vmwareOvfToolPath parameter to provide alternative path to the OVF Tool
- Changed $srmVaRootPassword, $srmVaAdminPassword and $srmDbPassword to mandatory inputs
Please …
> Enhancements to Install-SiteRecoveryManager

- PowerValidatedSolutions.psm1
- Refactor to use of Test-VCFConnection / Test-VCFAuthentication
- Refactor to use use of Test-VsphereConnection / Test-VsphereAuthentication
- Improvements in message output
- Refactored the handling of obtaining $dnsServer
- Refactored the handling of obtaining $ntpServer
- Added a -vmwareOvfToolPath parameter to provide alternative path to the OVF Tool
- Changed $vrmsVaRootPassword, and $vrmsVaAdminPassword to mandatory inputs …
> feat(pdr): Enhancements to Install-vSphereReplicationManager

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Refactor to use of Test-VCFConnection / Test-VCFAuthentication
- Improvements in message output
- Added pre-validation check
- Added support for Management/Workload Domain vCenter Registration
- Removed the need for $ssoAdminUser and $ssoAdminPass as inputs as obtained from SDDC Manager
Issue Number: Closes #154 
> feat(pdr): Enhancements to Connect-DRSolutionTovCenter

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Created Region for vSphere Replication Functions
- Added Request-VrmsToken to obtain a session token from vSphere Replication
- Added Get-VrmsApplianceDetail to obtain information on the vSphere Replication Appliance (used to session token)
- Created Region for Site Recovery Manager Functions
- Added Request-SrmToken to obtain a session token from Site Recovery Manager
- Added Get-SrmApplianceDetail to obtain information on the Site Recovery Manager (used to session token)
- Added internal function …
> feat(pdr): Session Token Request Functions

- PowerValidatedSolutions.psm1
- `Install-SiteRecoveryManager` fixed incorrect variable used for fqdn
- `Install-SiteRecoveryManager` added additional check for VAMI authentication
- `Connect-DRSolutionTovCenter` adding polling check of task id
- `Undo-DRSolutionTovCenter` fixed wording in outputs
- `Set-VrmsConfiguration` reverted to openssl method due to reliability issues
- `Set-SrmConfiguration` reverted to openssl method due to reliability issues
**Related to Existing …
> bug(pdr): Validation of DR Component Installation

- PowerValidatedSolutions.psm1
- Adjusted Set-WorkspaceOneNtpConfig to use primary NTP from SDDC Manager
- Removed the Undo alias as not required you just run it again
Issue Number: Closes #163 
> bug(iam): Address Workspace ONE Access NTP Configuration Issue

- PowerValidatedSolutions.psm1
- SampleScripts/ppm/README.md
- SampleScripts/ppm/passwordpolicymanager.ps1
- Improvements to the `README.md`.
- Added `Clear-Host` to script when it starts.
- Improvement to `Test-VCFAuthentication`.
- Implemented `Test-VCFConnection` / `Test-VCFAuthentication` around function to align with `PowerValidatedSolutions` cmdlets.
- Adjusted the order so all functions are defined before executing.
Closes #170 
> feat: Password Policy Manager Enhancements

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
New customer focused functions to cover expiration, complexity and account lockout as three distinct configuration options for ESXi.
- Request-EsxiPasswordExpiration
- Request-EsxiPasswordComplexity
- Request-EsxiAccountLockout
- Update-EsxiPasswordExpiration
- Update-EsxiPasswordComplexity
- Update-EsxiAccountLockout
- Created a new region for Password Management Functions for easier management
Moved the following functions to the deprecated section:
- Get-EsxiPasswordPolicy
- Set-EsxiPasswordExpirationPeriod
- …
> feat(iam): improvements to esxi password management

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Renamed and refactored functions:
- `Get-VcenterPasswordExpiration` from `Get-VCPasswordPolicy`
- `Set-VcenterPasswordExpiration` from `Set-VCPasswordPolicy`
- `Get-VcenterRootPasswordExpiration` from `Get-VCRootPasswordExpiry`
- `Set-VcenterRootPasswordExpiration` from `Set-VCPasswordExpiry`
- Removed function `Get-VCPasswordExpiry` as a duplicate.
- Added `Request-VcenterPasswordExpiration` cmdlet to retrieve the global password expiration policy for vCenter Server.
- Added `Request-VcenterRootPasswordExpiration` …
> feat(iam): enhancements to password vcenter password expiration

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Added `Get-LocalUserPasswordExpiration` cmdlet to retrieve the password expiration policy for a local user.
- Added `Set-LocalUserPasswordExpiration` cmdlet to configure the password expiration policy for a local user.
- Added `Request-LocalUserPasswordExpiration` cmdlet to retrieve the password expiration policy for a local user from a workload domain.
- Added `Update-LocalUserPasswordExpiration` cmdlet to configure the password expiration policy for a local user from any virtual machine.
Signed-off-by: Gary Blake …
> feat(iam): local user password expiration management

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Added `Publish-EsxiPasswordPolicy` cmdlet to retrieve the requested password policy for all ESXi hosts and output the details.
- Added `Invoke-PasswordPolicyManager` cmdlet to generate the Password Policy Manager report.
- 
> feat(iam): add drift to esxi password policies

- SampleScripts/iam/iamConfigureNsx.ps1
- SampleScripts/iam/iamConfigureVsphere.ps1
- SampleScripts/iam/iamConfigureWorkspaceOne.ps1
Remove password policy step from sample scripts
> feat: remove password policy step from sample scripts

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- README.md
- Added `Request-NsxtEdgePasswordExpiration` cmdlet to retrieve password expiration policy for NSX Manager nodes.
- Added `Update-NsxtEdgePasswordExpiration` cmdlet to updated password expiration policy for NSX Manager nodes.
- Added `Request-NsxtManagerPasswordExpiration` cmdlet to retrieve the password expiration for NSX Local Manager Local Users.
- Added `Update-NsxtManagerPasswordExpiration` cmdlet to update the password expiration for NSX Local Manager Local Users.
- Added `Start-PasswordPolicyConfig` cmdlet to …
> feat: password policy manager

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added Workspace ONE Access to Password Policy Manager Reports
- Added `Publish-WsaDirectoryPasswordPolicy` cmdlet to retrieve password policies for Workspace ONE Access Directory Users and output the details.
- Added `Publish-WsaLocalPasswordPolicy` cmdlet to retrieve password policies for Workspace ONE Access Local Users and output the details.
**Breaking …
> feat: add wsa to ppm report

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Update `Start-PasswordPolicyConfig` for Workspace ONE Access
- Fix for `Update-WsaLocalUserAccountLockout`
> feat: add wsa to remediation function

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updates `createGitHubAuthHeader` to require a user-provided, base64 encoded GitHub Token.
- Updates `Get-vRLIMarketplaceMetadata` to require a user-provided base64 encoded GitHub Token.
- Updates `Enable-vRLIContentPack` to require a user-provided, base64 encoded GitHub Token.
The GitHub token does not require any defined scope, it should only be read-only for public repositories.
**Related …
> fix: update content pack install functions

- PowerValidatedSolutions.psm1
- Updated Publish-SddcManagerPasswordExpiration to use Convert-CssClassStyle not Convert-CssClass
> fix: missed one change for Convert-CssClassStyle

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- README.md
- Updated release date in CHANGELOG.md
- Updated GUID in PowerValidatedSolutions.psd1
- Updated Version and Build in PowerValidatedSolutions.psd1
- Updated README.md
- Enhanced `Test-SSOAuthentication` cmdlet to include -SkipCertificateCheck parameter to handle platforms with self-signed certificates
Issue Number: Closes #207 
> chore: release updates

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Add-SsoPermission` to remove hardcoded vsphere.local
- Updated `Get-vCenterServerDetails` to add new ssoDomain value
Issue Number: Closes #218 
**VCF 4.5**
**VCF 5.0**
**VCF5.0 and Isolated Workload Domain
> feat: enhance `Add-SsoPermission` for isolated workload domains

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Add-vSphereRole` to support workload domain input.
- Updated CHANGELOG.md
- Updated ModuleVersion in PowerValidatedSolutions.psd1
Issue Number: Closes #220 
> feat: enhance add-vsphererole

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- README.md
- Updated release date in CHANGELOG.md
- Updated GUID in PowerValidatedSolutions.psd1
- Updated README.md
> chore: release changes

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Test-PowerValidatedSolutionsPrereq` cmdlet to perform a check for the installation of prerequisite PowerShell modules.
- Added `Show-PowerValidatedSolutionsOutput` cmdlet to handle formatting of output to the console when PowerVCF is not installed.
- Removed `Confirm-PSModule`
> feat: add prerequisite function

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fix `Test-VCFConnection` missing Export-ModuleMember switch.
- Updated version in PowerValidatedSolutions.psd1
Issue Number:  Closes #239 
> fix: missing export `Test-VCFConnection`

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
An issue was found with Get-GlobalPermissions where the response of the API didnt have ParsedHTML data. A code change is needed to read the html from response.content directly. 
```
PS C:\Users\Administrator>         $table = $response.ParsedHtml.body.getElementsByTagName("table")[3]
You cannot call a method on a null-valued expression.
At line:1 char:9
+         $table = $response.ParsedHtml.body.getElementsByTagName("tabl ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo …
```
> fix: update `Get-GlobalPermissions` html parsing

- PowerValidatedSolutions.psm1
- README.md
- Updates `VMware.PowerCLI` from v12.7.0 to v13.0.0.
- Updates `PowerVCF` from v2.2.0 to v2.3.0.
- Updates `VMware.vSphere.SsoAdmin` from v1.3.8 to v1.3.9.
- Updates `ImportExcel` from v7.1.1 to v7.8.4.
> chore(deps): bump module prerequisites

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- README.md
- Reviewed and Updated README.md
- Updated GUID in PowerValidatedSolutions.psd1
- Updated release date CHANGELOG.md
> chore: release preparation

- CHANGELOG.md
- vSphereRoles/operations-for-networks-vsphere-integration.role
- Added `operations-for-networks-vsphere-integration.role` file for Aria Operations for Networks to vSphere Integration.
Issue Number: Closes #253 
> feat: add operations for networks role file

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated all instance of "NSX-T Data Center" to "NSX" product name.
- Updated all instance of "NSX Management Cluster" to "NSX Manager cluster" term.
- Updated one instance of "NSX Local Manager" to "NSX Manager" term.
- Updated module version from v2.3.0.1001 to v2.3.0.1002.
No `CHANGELOG.md` update is necessary.
Update to product name and terms. …
> chore: update nsx product terms

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated CHANGELOG
- Updated `PowerValidatedSolutions.psd1` from Build 1003 to 1004
- Updated `Export-WsaJsonSpec` for VMware Cloud Foundation v4.5.1
> feat: add vcf 451 support for WSA deployment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-vRSLCMNtpServer` cmdlet with additional checking of the inputs against the exiting configuration.
Issue Number: Closes #263
> feat: enhancement to Add-vRSLCMNtpServer

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Enhanced `Set-NsxtManagerAuthPolicy` to handle password complexity parameters for NSX4.x
Closes #259
> feat: enhance `Set-NsxtManagerAuthPolicy` for NSX 4.x password complexity

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Enhance `Set-NsxtManagerAuthPolicy` to handle `hash_algorithm` parameter.
Closes #270 
> feat: enhance `Set-NsxtManagerAuthPolicy` for `hash_algorithm`

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Get-ESXiAdminGroup` cmdlet to retrieve the ESXi Admin Group configuration for an ESXi host.
- Added `Set-ESXiAdminGroup` cmdlet to configure the ESXi Admin Group configuation for an ESXi host.
- Updated `CHANGELOG.md`
- Bumped the build number in `PowerValidatedSolutions.psd1` from '2.4.0.1004' to '2.4.0.1005'
> feat: add esxi admin group cmdlets

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-WsaJsonSpec` to support VMware Cloud Foundation v5.0.0 and Workspace ONE Access v3.3.7.
- Enhanced `Export-vROPSJsonSpec` to support VMware Cloud Foundation v5.0.0 and vRealize Operations v8.10.2.
- Enhanced `Export-vRAJsonSpec` to support VMware Cloud Foundation v5.0.0 and vRealize Automation v8.11.2.
- Enhanced `Export-vRLIJsonSpec` to support VMware Cloud Foundation v5.0.0 and vRealize Log Insight v8.10.2. …
> feat: VCF 5 support for vRealize Suite

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `New-NsxtTier0BgpNeighborConfig` cmdlet to configure or update a BGP neighbor config for NSX Tier-0 gateway.
- Added `Get-NsxtLocaleService` cmdlet to get a paginated list of all Tier-0 locale-services.
- Added `Get-VCenterCEIP` cmdlet to retrieve the current status of Customer Experience Improvement Program (CEIP) for vCenter Server.
- Added `Set-VCenterCEIP` cmdlet to enable or disable Customer Experience Improvement Program (CEIP) for vCenter Server.
**Related to …
> feat: add new cmdlets

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
In order to have the best experience with our community, we recommend that you read the code of conduct and contributing guidelines before submitting a pull request.
By submitting this pull request, you confirm that you have read, understood, and agreed to the project's code of conduct and contributing guidelines.
Please use conventional commits to format the title of the pull request and the commit messages.
For more information, please refer to https://www.conventionalcommits.org.
- **Breaking Change** Fixed `Request-vRLIToken` to use new bearer token request for vRealize Log Insight.
Closes #279
> fix: update vrli api token request

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Update-vRSLCMPSPack` to refresh and update Product Support Packs in vRealize Suite Lifecycle Manager.
- Added `Get-vRSLCMPSPack` cmdlet to refresh the metadata for Product Support Packs in vRealize Suite Lifecycle Manager.
- Added `Install-vRSLCMPSPack` cmdlet to install a Product Support Packs in vRealize Suite Lifecycle Manager.
N/A
None
> feat: add vrslcm product support pack functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Request-VcenterApiToken` to use `-skipCertificateCheck` switch if `$PSEdition` is "Core" and `$PSVersionTable.OS` is "Linux".
- Bump module version to v2.5.0.1004.
With this change, the following cmdlet in `VMware.CloudFoundation.Reporting` will work on PowerShell 7 on Linux.
```powershell
PS /home/vmware/.local/share/powershell/Modules/PowerValidatedSolutions/2.5.0.1003> Import-Module ./PowerValidatedSolutions.psd1
PS /home/vmware/.local/share/powershell/Modules/PowerValidatedSolutions/2.5.0.1003> Request-VcenterBackupStatus -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -domain sfo-m01
Component : vCenter Server
Resource  : vCenter Server Backup Operation
Element   : sfo-m01-vc01.sfo.rainpole.io
Domain …
```
> fix: update `Request-VcenterApiToken` for pwsh and linux

- CHANGELOG.md
- SampleScripts/iam/iamConfigureNsx.ps1
- SampleScripts/iam/iamConfigureVsphere.ps1
- SampleScripts/iam/iamConfigureWorkspaceOne.ps1
- SampleScripts/iam/iamSolutionInteroperability.ps1
- SampleScripts/iam/iamUndoDeployment.ps1
- Enhanced `iamConfigureVsphere.ps1` script for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- Enhanced `iamConfigureWorkspaceOne.ps1` script for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- Enhanced `iamConfigureNsx.ps1` script for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- Enhanced `iamUndoDeployment.ps1` script for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- Enhanced `iamSolutionInteroperability.ps1` script for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
N/A
N/A
> feat: enhancements to iam scripts

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Updated `Add-vROPSAdapterSddcHealth` cmdlet to support both REMOTE and CLOUD_PROXY collectors.
Closes #297 
N/A
> fix: support for cloud proxies in `Add-vROPSAdapterSddcHealth`

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleScripts/dri/driConfigureSupervisorCluster.ps1
- SampleScripts/dri/driDeployTanzuCluster.ps1
- SampleScripts/dri/driUndoDeployment.ps1
- SampleScripts/iam/iamConfigureNsx.ps1
- SampleScripts/iam/iamConfigureVsphere.ps1
- SampleScripts/iam/iamConfigureWorkspaceOne.ps1
- SampleScripts/iam/iamSolutionInteroperability.ps1
- SampleScripts/iam/iamUndoDeployment.ps1
- SampleScripts/ila/ilaConfigureVrealizeLogInsight.ps1
- SampleScripts/ila/ilaDeployVrealizeLogInsight.ps1
- SampleScripts/ila/ilaSolutionInteroperability.ps1
- SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
- SampleScripts/ila/ilaUndoVrealizeLogInsight.ps1
- SampleScripts/iom/iomConfigureVrealizeOperations.ps1
- SampleScripts/iom/iomDeployVrealizeOperations.ps1
- SampleScripts/iom/iomSolutionInteroperability.ps1
- SampleScripts/pca/pcaDeployVrealizeAutomation.ps1
- Enhanced Scripts in the SampleScripts\dri folder, for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- `driConfigureSupervisorCluster.ps1`
- `driDeployTanzuCluster.ps1`
- `driUndoDeployment.ps1`
- Enhanced Scripts in the SampleScripts\iam folder, for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- `iamConfigureVsphere.ps1`
- `iamConfigureWorkspaceOne.ps1`
- `iamConfigureNsx.ps1`
- `iamUndoDeployment.ps1`
- `iamSolutionInteroperability.ps1`
- Enhanced Scripts in the SampleScripts\ila folder, for VMware Cloud Foundation 5.0 support (for full details see change log details within the script file).
- `ilaConfigureVrealizeLogInsight.ps1`
- `ilaDeployVrealizeLogInsight.ps1`
- …
> feat: update sample scripts for vcf5

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-vRLISmtpConfiguration` cmdlet with a 2 second delay to ensure the API call completes.
- Enhanced `Add-vRLIAuthenticationWSA` cmdlet with a 2 second delay to ensure the API call completes.
- Enhanced `Add-vRLIAgentGroup` cmdlet with a 2 second delay to ensure the API call completes.
Closes #310 
Closes #311 
Closes #312
N/A
> fix: address ila post-validation issues

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Update formatting across NSX Functions.
N/A
N/A
> chore: update formatting across nsx functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleNotifications/vrli-iom-alerts.json
- SampleNotifications/vrli-vcf-alerts.json
- SampleNotifications/vrli-vrslcm-alerts.json
- Added `Set-vRLIAlert` cmdlet to enable an alert in vRealize Log Insight.
- Added `Update-vRLIAlert` cmdlet to configure an email address for an alert in vRealize Log Insight.
- Added `Enable-vRLIAlert` cmdlet to enable vRealize Log Insight alerts based on a supplied JSON file.
- Added `Disable-vRLIAlert` cmdlet to disable vRealize Log Insight alerts based ona supplied JSON file.
- Added `vrli-iom-alerts.json` to \SampleNotification folder for Intelligent Operations Management alerts.
- Added `vrli-vcf-alerts.json` to \SampleNotification folder for VMware Cloud Foundation alerts.
- Adedd `vrli-vrslcm-alerts.json` to \SampleNotification folder for vRealize Suite Lifecycle Manager alerts.
N/A
N/A
> feat: add functions to enable vrli alerts

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleYaml/sfo-w01-tkc01-cluster.yaml
- Fixed typo in `New-vROPSDeployment` message output.
- Fixed typo in `New-vRADeployment` message output.
- Fixed typo in `New-WSADeployment` message output.
- Enhanced `Add-SupervisorClusterLicense` to improve error handling.
- Updated version in `SampleYaml/sfo-w01-tkc01-cluster.yaml`
n/a
n/a
> fix: address various issues observed

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Get-LocalUserPasswordExpiration` cmdlet to allow for the use of a `-sudo` to elevate the privileges to run the command on a virtual appliance when the user is not `root`.
- Enhanced `Set-LocalUserPasswordExpiration` cmdlet to allow for the use of a `-sudo` to elevate the privileges to run the command on a virtual appliance when the user is not `root`.
- Updated module version to 2.7.0.1001.
Closes #287
> feat: add sudo option for chage cmds

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-ContentLibrary` cmdlet to check the VMware Cloud Foundation version when adding a subscribed content library. If the version is 5.0.0 or later and the `-subscriptionUrl` parameter is set to `wp-content.vmware.com`, a warning message is displayed and the cmdlet exits.
- Updated module version to 2.7.0.1002
Closes #318
> feat: add version check based on `-subscriptionUrl`

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Add-vROPSVcenterCredential` cmdlet to create a VMware Cloud Foundation credential in Aria Operations.
Closes #351 
N/A
> feat: add vcenter server credential to aria operations

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated cmdlet descriptions and examples for Aria Suite, formerly known as vRealize Suite, products to use the new Aria names. 
- Updated module version to v2.7.0.1008.
**Note:** No changes to the names of the cmdlets or variables. Not in scope.
> chore: aria rebranding - cmdlet content

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-vRAJsonSpec` to support VMware Cloud Foundation v5.1.0 and vRealize Automation v8.12.2.
N/A
N/A
> chore: update vra version for 5.1 support

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Updated `Request-VcenterApiToken` to remove the `$PSVersionTable.OS` check for PowerShell Core.
- Updated `Request-VrmsToken` to remove the `$PSVersionTable.OS` check for PowerShell Core.
- Updated the `CHANGELOG.md`.
- Updated the module version to v2.7.0.1018.
Closes #368
> fix: remove pwsh version os check

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/index.md
- docs/snippets/install-module.ps1
- Updated `PowerVCF` from v2.3.0 to v2.4.0.
- Updated `VMware.PowerCLI` from v13.0.0 to v13.1.0.
- Updated documentation for PowerShell 7 support.
- Updated the `CHANGELOG.md`.
- Updated the module version to v2.7.0.1017.
Closes #58
> chore(deps): update dependencies

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-vRLIJsonSpec` to support deployment of VMware Aria Operations for Logs OVA using vSphere Content Library.
- Enhanced `New-vRLIDeployment` to support deployment of VMware Aria Operations for Logs OVA using vSphere Content Library.
- Enhanced `Export-VROPsJsonSpec` to support deployment of VMware Aria Operations OVA using vSphere Content Library.
- Enhanced `New-vROPsDeployment` to support deployment of VMware Aria Operations OVA using vSphere Content Library.
- Enhanced `Export-VraJsonSpec` to support deployment of VMware Aria Automation OVA using vSphere Content Library.
- Enhanced `New-VraDeployment` to support deployment of VMware Aria Automation OVA using vSphere Content Library.
- Enhanced `Export-WsaJsonSpec` to support deployment of Workspace ONE Access OVA using …
> feat: deploy aria suite using vsphere content library

- PowerValidatedSolutions.psm1
- Update descriptions and message outputs to use official VMware Aria naming
N/A
N/A
> chore: vmware aria branding udpates

- docs/index.md
- docs/requirements.txt
- Adds VMware Cloud Foundation 5.1 for the v2.7.0 release.
- Removes VMware Cloud Foundation 4.3 for the v2.7.0 release.
- Updates MkDocs dependencies.
> docs: update docs

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Enhanced `Export-vROPSJsonSpec` to support VMware Cloud Foundation v5.1.0 and VMware Aria Operations v8.14.0.
- Enhanced `Export-vRLIJsonSpec` to support VMware Cloud Foundation v5.1.0 and VMware Aria Operations for Logs v8.14.0.
- Enhanced `Export-vRAJsonSpec` to support VMware Cloud Foundation v5.1.0 and VMware Aria Automation v8.14.0.
N/A
N/A
> feat: update aria version

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Export-IlaJsonSpec` cmdlet to generate a JSON specification file for Intelligent Logging and Analytics.
- Added `Invoke-IlaDeployment` cmdlet to perform an end-to-end deployment of Intelligent Logging and Analytics.
- Added `Invoke-UndoIlaDeployment` cmdlet to perform removal of Intelligent Logging and Analytics.
- Enhanced `Add-vRLIAuthenticationWSA` cmdlet to check for connectivity and authentication to Workspace ONE Access.
- Enhanced `Add-WorkspaceOneRole` cmdlet for better pre and post validation.
N/A
N/A
> feat: ila deploy and undo in single functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Set-NsxtRole` cmdlet to support adding roles to LDAP users.
Closes #399 
N/A
> feat: add support for nsx roles to ldap users

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `New-WSADeployment` cmdlet to better handle checking for reporting a missing Cross-Instance Datacenter.
N/A
N/A
> feat: enhance error handling

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed missing load balancer for JSON spec
N/A
N/A
> feat: add load balancer for wsa

- PowerValidatedSolutions.psm1
- Applied code formatting standards to Test and Utility functions
N/A
N/A
> chore: code formatting for test and utility functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Applied code formatting standards to Active Directory and Cloud Foundation functions.
- Fixed `Get-WSAServerDetails` cmdlet where incorrect initial check was looking for VMware Aria Automation not VMware Aria Suite Lifecycle.
- Enhanced `Get-WSAServerDetails` cmdlet to include credentials and node code for the VCF-Aware Workspace ONE Access instance.
N/A
N/A
> chore: code formatting for ad and cloud foundation functions

- PowerValidatedSolutions.psm1
- Applied code formatting standards to vSphere functions.
N/A
N/A
> chore: code formatting for vsphere functions

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- Applied code formatting standards to Workspace ONE Access functions.
N/A
N/A
> chore: code formatting for wsa functions

- PowerValidatedSolutions.psm1
- Applied code formatting standards to VMware Aria Automation and Orchestrator functions.
N/A
N/A
> chore: code formatting for aria automation and orchestrator functions

- PowerValidatedSolutions.psm1
- Applied code formatting standards to VMware Aria Operations functions.
N/A
N/A
> chore: code formatting for aria operations functions

- PowerValidatedSolutions.psm1
- Applied code formatting standards to VMware Aria Operations for Logs functions.
N/A
N/A
> chore: code formatting for aria operations for logs functions

- PowerValidatedSolutions.psm1
- Applied code formatting standards to VMware Cloud functions.
N/A
N/A
> chore: code formatting for cloud functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-vRLIJsonSpec` to support automatic creation of anti-affinity rule.
Closes #429 
N/A
> feat: anti-affinity rule for ops for logs

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Improve error handling for input files
N/A
N/A
> fix: error handling for invoke-iamdeployment

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Locate `Get-`, `Set-` and `Remove-vRSLCMMyVmwareAccount` cmdlets together in the file
- Enhanced `Get-vRSLCMSshStatus` cmdlet with check for token.
- Enhanced `Set-vRSLCMSshStatus` cmdlet with check for token.
No update to CHANGELOG.md as functions are not released yet.
N/A
N/A
> feat: add vrslcm api functions

- PowerValidatedSolutions.psm1
- Fix the formatting for each function following changes made for doc updates.
N/A
N/A
> fix: formatting issue following doc updates

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Adds support for vSphere Replication
Functionality has been verified via unit testing. No breaking changes are included.
Does not close an issue
> Feature: Add support to configure vSphere Replication

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- No updated for CHANGELOG.md as enhancements are based on testing and non-released cmdlets.
N/A
N/A
> Feat enhancements to ila deployment error handling

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Undo-vRADeployment` cmdlet to remove VMware Aria Automation from VMware Aria Suite Lifecycle.
- Enhanced `Export-vRAJsonSpec` cmdlet to generate the JSON specification file using the Private Cloud Automation JSON specification file.
N/A
N/A
> feat: enhance aria automation deployment

- PowerValidatedSolutions.psm1
- Remove wsa groups from `Export-IamJsonSpec`
N/A
N/A
> fix: remove wsa groups from export-iamjsonspec

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Remove check for workbook for `Invoke-UndoIomDeployment`
N/A
N/A
> fix: remove check for workbook for invoke-undoiomdeployment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Start-vRSLCMSnapshot` cmdlet to start a snapshop operation of VMware Aria Suite Lifecycle.
- Enhanced `Update-vRSLCMPSPack` cmdlet to perform a snapshot as part of the workflow and improved status checks.
N/A
N/A
> feat: add support for pspack update and snapshots

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-IlaJsonSpec`:
- Added contentLibraryName
- Enhanced `Invoke-IlaDeployment`
- Added Creating a vSphere Content Library
- Enhanced `Export-IomJsonSpec`:
- Added contentLibraryName
- Enhanced `Invoke-IomDeployment`
- Added Creating a vSphere Content Library
- Added `Import-ContentLibraryItem` cmdlet to support adding files to a vSphere Content Library.
N/A
N/A
> feat: improvements to ila & iom oneclick

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Request-AslcmBundle` cmdlet to download the VMware Aria Suite Lifecycle bundle in SDDC Manager.
- Added `New-AslcmDeployment` cmdlet to perform the deployment of VMware Aria Suite Lifecycle using SDDC Manager.
- Added `Install-AslcmCertificate` cmdlet to install a signed certificate for VMware Aria Suite Lifecycle using SDDC Manager.
N/A
N/A
> feat: add functions to support aria suite lifecycle deployment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Various updates to improve or address issues found whilst performing oneclick testing
- Added `Invoke-UndoPcaDeployment` cmldet to perform an end-to-end removal of Private Cloud Automation.
N/A
N/A
> fix: address oneclick issues

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Various improvement to oneClick during end-to-end testing.
- Enhanced `Add-vCenterGlobalPermission` cmdlet to check for the existence of the vCenter Server role.
N/A
N/A
> Fix address issues found during end to end testing

- docs/index.md
- docs/install.md
- docs/update.md
- mkdocs.yml
Updates the documentation to provide instructions for:
- Connected Environment (internet access)
- Disconnected Environment (dark-site / air-gapped)
> docs: update for connected and disconnected

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Add support for Site Recovery Manager Protection Groups
Ref: #62
> Feature: Add support for SRM Protection Groups

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Connect-AslcmUpgradeIso` cmdlet to connect an upgrade ISO on VMware Aria Suite Lifecycle.
- Added `Disconnect-AslcmUpgradeIso` cmdlet to disconnect an upgrade ISO from VMware Aria Suite Lifecycle.
N/A
N/A
> feat: add support for mounting iso to aslcm

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Adds support for SRM Recovery Plans
Closes #62
Closes #63
> feat: add support for srm recovery plans

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Deploy-PhotonAppliance` cmdlet to deploy the Photon appliance for the Health Reporting and Monitoring validated solution.
- Added `Remove-PhotonAppliance` cmdlet to remove the Photon appliance for the Health Reporting and Monitoring validated solution.
N/A
N/A
> feat: add support for photon appliance deployment

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Added support for targeting multiple VMs for creating and removing vSphere Replications
Fixed return value evaluation and changed $name parameter to $vmName to align with other functions in Get-VrmsReplication
> enhance: Support multiple VM target with Add-vSphereReplication and Undo

- docs/documentation/functions/solutions/inv/index.md
- docs/documentation/functions/solutions/iom/index.md
- docs/documentation/functions/solutions/lcm.md
- docs/documentation/functions/solutions/pdr/index.md
Updates for consistency and correctness.
> docs: documentation updates

- CHANGELOG.md
> chore: release v2.8.0

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/index.md
- docs/snippets/install-module.ps1
Bumps `PowerVCF` from 2.4.0 to 2.4.1.
> chore(deps): bump powervcf from 2.4.0 to 2.4.1

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- docs/index.md
- docs/install.md
Removes support for Microsoft Windows PowerShell 5.1.
Use Microsoft PowerShell 7.2.0 or later.
> chore(deps): support pwsh 7.2 and later

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
- mkdocs.yml
Adds ` Get-vRSLCMProductPassword ` to be consumed in downstream in `VMware.CloudFoundation.PowerManagement` to get the decrypted password from the Locker for the purposes of authentication.
> feat: add `Get-vRLSCMProductPassword`

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-automation/New-vRADeployment.md
Removes support for:
- Deployment of VMware Aria product components earlier than 8.14.0
- Deployment for VMware Aria products on VMware Cloud Foundation earlier than 4.5.2.
Updates:
- `Export-vRLIJsonSpec`
- `New-vRLIDeployment`
- `Export-vROPsJsonSpec`
- `New-vROPSDeployment`
- `Export-vRAJsonSpec`
- `New-vRADeployment`
- `Export-WsaJsonSpec`
> chore: remove aria component versions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Add message stating starting the JSON generation process for DRI
- Add message stating starting the JSON generation process for HRM
- Enhanced `Deploy-PhotonAppliance` cmdlet error handling to verify if the OVA was deployed before trying to power it on.
- Enhanced `Get-WSAServerDetail` cmdlet to handle single node Workspace ONE Access deployments.
N/A
N/A
> feat: end-to-end testing of oneclicks

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Accommodates VCF 4.x and 5.x by making Content Library optional.
Ref: #478
Resolves issue with enabling a Supervisor in VCF 5.0+ where a Content Library is automatically created during the instantiation process. VCF 4.x still requires a Content Library to be created manually.
Will submit PR in PlatformTools to fully resolve the issue.
Closes #478
> fix: Error while deploying a Supervisor

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/ccm/Export-CcmJsonSpec.md
- docs/documentation/functions/solutions/ccm/Invoke-CcmDeployment.md
- docs/documentation/functions/solutions/ccm/Invoke-UndoCcmDeployment.md
- docs/documentation/functions/solutions/ccm/index.md
- mkdocs.yml
- Added `Export-CcmJsonSpec` cmdlet to generate a JSON specification file for Cross Cloud Migration.
- Added `Invoke-CcmDeployment` cmdlet to perform an end-to-end deployment of Cross Cloud Migration.
- Added `Invoke-UndoCcmDeployment` cmdlet to perform removal of Cross Cloud Migration.
- Added documentation for new functions.
N/A
N/A
> feat: add oneclick for ccm

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced One-Click `Invoke-` cmdlets for better message output:
- `Invoke-IamDeployment`
- `Invoke-UndoIamDeployment`
N/A
N/A
> feat: enhancements to message output for iam one-click

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced One-Click `Invoke-` cmdlets for better message output:
- `Invoke-DriDeployment`
- `Invoke-UndoDriDeployment`
N/A
N/A
> feat: enhancements to message output for dri one-click

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced One-Click `Invoke-` cmdlets for better message output:
- `Invoke-IlaDeployment`
- `Invoke-UndoIlaDeployment`
N/A
N/A
> feat: enhance message output for ila one-click

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced One-Click `Invoke-` cmdlets for better message output:
- `Invoke-HrmDeployment`
- `Invoke-UndoHrmDeployment`
- `Invoke-CbwDeployment`
- `Invoke-UndoCbwDeployment`
- `Invoke-CbrDeployment`
- `Invoke-UndoCbrDeployment`
- `Invoke-CcmDeployment`
- `Invoke-UndoCcmDeployment`
N/A
N/A
> feat: enhance message output for hrm, cbw, cbr, ccm oneclick

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/active-directory/Get-ADPrincipalGuid.md
- docs/documentation/functions/active-directory/Test-ADAuthentication.md
- docs/documentation/functions/site-recovery-manager/Add-RecoveryPlan.md
- docs/documentation/functions/solutions/pdr/Export-PdrJsonSpec.md
- docs/documentation/functions/solutions/pdr/index.md
- docs/documentation/functions/vsphere-replication/Add-EsxiVrmsVMkernelPort.md
- docs/documentation/functions/vsphere-replication/Add-vSphereReplication.md
- docs/documentation/functions/vsphere-replication/Connect-DRSolutionTovCenter.md
- docs/documentation/functions/vsphere/Move-VMtoFolder.md
- mkdocs.yml
- Added `Export-PdrJsonSpec` cmdlet to generate a JSON specification file for Site Protection and Disaster Recovery.
- Fixed `Add-EsxiVrmsVMkernelPort` pre-validation to actually compare server count so that it skips if configured.
- Enhanced `Move-VMtoFolder` cmdlet to check if the VM has already been moved and also handle multiple vCenter Server connections.
- Enhanced `Install-VamiCertificate` cmdlet to check the path to the certificate files.
- Updated and Added documentation
N/A
N/A
> feat: prepare for pdr oneclick

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/site-recovery-manager/Add-ProtectionGroup.md
- docs/documentation/functions/site-recovery-manager/Add-RecoveryPlan.md
- docs/documentation/functions/site-recovery-manager/Add-SrmLicenseKey.md
- docs/documentation/functions/site-recovery-manager/Add-SrmMapping.md
- docs/documentation/functions/site-recovery-manager/Add-SrmProtectionGroup.md
- docs/documentation/functions/site-recovery-manager/Add-SrmRecoveryPlan.md
- docs/documentation/functions/site-recovery-manager/Add-SrmRecoveryPlanCalloutStep.md
- docs/documentation/functions/site-recovery-manager/Get-SrmVamiCertificate.md
- docs/documentation/functions/vsphere-replication/Get-VrmsVamiCertificate.md
- Enhanced `Get-VrmsVamiCertificate` cmdlet to retrieve the installed Certificate Authority certificates from the vSphere Replication Appliance.
- Enhanced `Get-SrmVamiCertificate` cmdlet to retrieve the installed Certificate Authority certificates from the Site Recovery Manager Appliance.
- Addressed issues with documentation and updated where needed.
N/A
N/A
> feat: certificate managment of srm & vrms

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/pdr/Invoke-PdrDeployment.md
- docs/documentation/functions/solutions/pdr/Invoke-UndoPdrDeployment.md
- docs/documentation/functions/solutions/pdr/index.md
- mkdocs.yml
- Added `Invoke-PdrDeployment` cmdlet to perform an end-to-end deployment of Site Protection and Disaster Recovery.
- Added `Invoke-UndoPdrDeployment` cmdlet to perform removal of Site Protection and Disaster Recovery.
- Added documentation
N/A
N/A
> feat: add pdr one-click

- .vscode/extensions.json
- .vscode/settings.json
- Add recommended extensions: `.vscode/extensions.json`
- Add recommended user settings: .`vscode/settings.json`
This will ensure that contributors generally have the same recommended extensions and workspace settings - for example, for code formatting.
> chore: add .vscode settings

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Invoke-***Deployment` and `Invoke-Undo***Deployment` functions by switching them to use the ew messageHandler function.
- Various issues addresed.
N/A
N/A
> feat: oneclick end-to-end testing

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductDetails.md
Adds the `vmid` option to `Get-vRSLCMProductDetails`.
> feat: add `vmid` option to `Get-vRSLCMProductDetails`

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- docs/documentation/functions/certificates/Invoke-GenerateChainPem.md
- docs/documentation/functions/certificates/Invoke-GeneratePrivateKeyAndCsr.md
- docs/documentation/functions/certificates/Invoke-RequestSignedCertificate.md
Adds following new functions to transition capability from CertGenVVS script to this module:
1. `Invoke-GeneratePrivateKeyAndCsr`
2. `Invoke-RequestSignedCertificate`
3. `Invoke-GenerateChainPem`
Closes #489
> feat: transition cetgenvvs to module

- docs/documentation/user-guide/certificate-generation.md
- mkdocs.yml
Adds a user guide for certificate generation with the transitioned functions.
> docs: add certificate generation guide

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated OneClick to use node A for the initial configuration
N/A
N/A
> fix: add directory to global wsa

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhancement to Add-vRLIAuthenticationGroup
N/A
N/A
> feat: enhancement to Add-vRLIAuthenticationGroup

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Fixes an issue where -masterDnsServers, -masterNtpServers, and -workerDnsServers parameters were presented as string values when array values are required.
> fix: Invoke-DriDeployment fails - parameter format

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated affinityRule for vrli and vrops
- Fix issue with message output for `Add-vROPSNsxCredential`
- Remove anti-affinity procedure from `Invoke-IomDeployment`
N/A
N/A
> fix: addressing pipeline issues

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated the minimum version to 8.16.0
N/A
N/A
> fix: bump vrlsmc version check

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `Start-ValidatedSolutionMenu` cmdlet to load the Validated Solution main menu.
- Added `Start-AriaSuiteLifecycleMenu` cmdlet to load the VMware Aria Suite Lifecycle sub-menu.
- Added `Start-WorkspaceOneAccessMenu` cmdlet to load the Workspace ONE Access sub-menu.
- Added `Start-IamMenu` cmdlet to load the Identity and Access Management sub-menu.
- Added `Start-DriMenu` cmdlet to load the Developer Ready Infrastructure sub-menu.
- Added `Start-IlaMenu` cmdlet to load the Intelligent Logging and Analytics sub-menu.
- Added `Start-InvMenu` cmdlet to load the Intelligent Network Visibility sub-menu.
- Added `Start-PcaMenu` cmdlet to load the Private Cloud Automation sub-menu.
- Added `Start-PdrMenu` cmdlet to load the Site Protection and Disaster Recovery sub-menu.
- Added …
> feat: validated solutions menus

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/workspace-one-access/Export-WsaJsonSpec.md
- docs/documentation/functions/workspace-one-access/Invoke-WsaDirectorySync.md
- docs/documentation/functions/workspace-one-access/New-WSADeployment.md
- Enhanced `Export-GlobalWsaJsonSpec` cmdlet to add missing items pulled from the PLanning and Preparation Workbook to support `Export-WsaJsonSpec`.
- Enhanced `Export-WsaJsonSpec` cmdlet to generate the API based deployment JSON spec for Workspace ONE Access using VMware Aria Suite Lifecycle using the global JSON.
- Updated supporting documentation.
N/A
N/A
> feat: convert export-wsajsonspec to use the global json file

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Request-AriaNetworksToken.md
- mkdocs.yml
- Added `Request-AriaNetworksToken` cmdlet to obtain an authorization token from VMware Aria Operations for Networks.
- Added documentation.
N/A
N/A
> feat: add Request-AriaNetworksToken cmdlet

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/dri/Test-DriPrerequisite.md
- docs/documentation/functions/solutions/dri/index.md
- docs/documentation/functions/solutions/iam/Test-IamPrerequisite.md
- docs/documentation/functions/solutions/iam/index.md
- docs/documentation/functions/solutions/pca/Test-PcaPrerequisite.md
- docs/documentation/functions/solutions/pca/index.md
- mkdocs.yml
- Fixed `Get-ADPrincipalGuid` cmdlet to handle failed credentials correctly.
- Added cmdlets to verify prerequisites before attempting to deploy a Validated Solutions:
- Added `Test-IamPrerequisite` cmdlet to verify prerequisites for Identity and Access Management.
- Added `Test-DriPrerequisite` cmdlet to verify prerequisites for Developer Ready Infrastructure.
- Added `Test-PcaPrerequisite` cmdlet to verify prerequisites for Private Cloud Automation.
N/A
N/A
> feat: prerequisite functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/dri/index.md
- docs/documentation/functions/solutions/ila/index.md
- docs/documentation/functions/solutions/iom/Test-IomPrerequisite.md
- docs/documentation/functions/solutions/iom/index.md
- mkdocs.yml
- Added `Test-IomPrerequisite` cmdlet to verify prerequisites for Intelligent Operations Management.
- Added docuemntation.
N/A
N/A
> feat: add iom prerequisite function

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/cbr/Test-CbrPrerequisite.md
- docs/documentation/functions/solutions/cbr/index.md
- docs/documentation/functions/solutions/cbw/Test-CbwPrerequisite.md
- docs/documentation/functions/solutions/cbw/index.md
- docs/documentation/functions/solutions/ccm/Test-CcmPrerequisite.md
- docs/documentation/functions/solutions/ccm/index.md
- docs/documentation/functions/solutions/hrm/Remove-PhotonAppliance.md
- docs/documentation/functions/solutions/hrm/Test-HrmPrerequisite.md
- docs/documentation/functions/solutions/hrm/index.md
- mkdocs.yml
- Added `Test-HrmPrerequisite` cmdlet to verify prerequisites for Health Reporting anf Monitoring.
- Added `Test-CbwPrerequisite` cmdlet to verify prerequisites for Cloud-Based Workload Protection.
- Added `Test-CbrPrerequisite` cmdlet to verify prerequisites for Cloud-Based Ransomware Recovery.
- Added `Test-CcmPrerequisite` cmdlet to verify prerequisites for Cross Cloud Mobility.
- Added Documentation
N/A
N/A
> feat: additional prerequisite functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-IomDeployment` cmdlet where the wrong service account was being assigned a vCenter Server global permission.
Closes #535 
N/A
> fix: vrops adapter creation

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-automation/Request-vRAMscaSignedCertificate.md
- docs/documentation/functions/aria-suite/aria-operations-logs/Request-vRLIMscaSignedCertificate.md
- docs/documentation/functions/aria-suite/aria-operations/Request-vROPSMscaSignedCertificate.md
- docs/documentation/functions/certificates/Invoke-GenerateChainPem.md
- docs/documentation/functions/certificates/Invoke-GeneratePrivateKeyAndCsr.md
- docs/documentation/functions/certificates/Invoke-RequestSignedCertificate.md
- docs/documentation/functions/certificates/Request-SignedCertificate.md
- docs/documentation/functions/solutions/ila/index.md
- docs/documentation/functions/solutions/iom/index.md
- docs/documentation/functions/solutions/pca/index.md
- mkdocs.yml
- Enhanced `Invoke-GeneratePrivateKeyAndCsr` cmdlet for error handling and message output.
- Enhanced `Invoke-RequestSignedCertificate` cmdlet for error handling and message output.
- Enhanced `Invoke-GenerateChainPem` cmdlet for error handling and message output.
- Added `Request-vRLIMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Operations for Logs.
- Added `Request-vROPSMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Operations.
- Added `Request-vRAMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Automation.
- Updated documentation.
N/A
N/A
> feat: enhance certificate functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added `New-PowerValidatedSolutionsLogFile` cmdlet to enable support for a log file when using the VMware Validated Solutions menu.
N/A
N/A
> feat: add support for logging output to a file

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Get-AriaNetworksDataSource.md
- docs/documentation/functions/aria-suite/aria-operations-networks/Get-AriaNetworksNodes.md
- docs/documentation/functions/aria-suite/aria-operations-networks/Request-AriaNetworksToken.md
- mkdocs.yml
Added functions for Intelligent Network Visibility.
> feat: add inv functions

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added internal `Test-Prereq*` functions for code reuse
- Enhanced existing `Test-*Prerequisite` functions to use new internal functions.
N/A
N/A
> feat: enhance prerequisite functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/pdr/Test-PdrPrerequisite.md
- docs/documentation/functions/solutions/pdr/index.md
- mkdocs.yml
- Added `Test-PdrPrerequisite` cmdlet to verify prerequisites for Site Protection and Disaster Recovery.
N/A
N/A
> feat: add prerequisite check for pdr

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleYaml/tanzuClusterTemplate.yaml
- Enhanced `Invoke-DriDeployment` cmdlet to auto-generate the YAML file based on vSphere versions.
Closes #590 
N/A
> fix: enhance invoke-drideployment to auto-generate yaml file

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/site-recovery-manager/Undo-SrmMapping.md
- docs/documentation/functions/vsphere-replication/Test-VrSdkAuthentication.md
- mkdocs.yml
- Added `Test-VrmsRegistration` cmdlet as an internal function to check for registration of vSphere Replication in vCenter Server.
- Added `Test-SrmRegistration` cmdlet as an internal function to check for registration of Site Recovery Manager in vCenter Server.
- Added `Test-VrSdkAuthentication` cmdlet to verify authentication using the PowerCLI Sdk module for vSphere Replication.
- Minor improvements of `Invoke-UndoPdrDeployment`.
- Documentation updates.
N/A
N/A
> Feat pdr improvements

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Updated `Export-vRAJsonSpec` to support 8.16.2.
N/A
N/A
> feat: update aria automation version and remove eogs items

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Update-vRSLCMPSPack.ps1
- config.PowerValidatedSolutions
- docs/documentation/functions/aria-suite/aria-suite-lifecycle/Import-vRSLCMPSPack.md
- docs/documentation/functions/solutions/lcm/Invoke-VrslcmUndoDeployment.md
- docs/documentation/functions/solutions/lcm/index.md
- mkdocs.yml
- Enhanced `Export-WsaJsonSpec` cmdlet to use `config.PowerValidatedSolutions` configuration file for mapping Workspace ONE Access version.
- Enhanced `Export-vRLIJsonSpec` cmdlet to use `config.PowerValidatedSolutions` configuration file for mapping VMware Aria Operations for Logs version.
- Enhanced `Export-vROPsJsonSpec` cmdlet to use `config.PowerValidatedSolutions` configuration file for mapping VMware Aria Operations version.
- Enhanced `Export-vRAJsonSpec` cmdlet to use `config.PowerValidatedSolutions` configuration file for mapping VMware Aria Automation version.
- Enhanced `Add-ContentLibrary` cmdlet to not exit the workflow when checking for the version of VMware Cloud Foundation.
- Enhanced `Invoke-vRSLCMDeployment` cmdlet to use the internal `messageHandler` function for …
> feat: use config file for aria versions

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Addressed placement of pause for manual Product Support Pack install.
N/A
N/A
> fix: pause for ps pack manual install

- CHANGELOG.md
- PowerValidatedSolutions.psm1
- docs/documentation/functions/certificates/Get-MscaRootCertificate.md
add cmdlet 'get-mscaRootCertificate' to epxort root certificate from msca.
Signed-off-by: Kevin Teng <kevin.teng@broadcom.com> 
> feat:add_export_root_ca_cmdlet

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- config.PowerValidatedSolutions
- docs/documentation/functions/solutions/ila/Request-IlaMscaSignedCertificate.md
- docs/documentation/functions/solutions/ila/index.md
- docs/documentation/functions/solutions/iom/Request-IomMscaSignedCertificate.md
- docs/documentation/functions/solutions/iom/index.md
- docs/documentation/functions/solutions/pca/Request-PcaMscaSignedCertificate.md
- docs/documentation/functions/solutions/pca/index.md
- docs/documentation/functions/solutions/wsa/index.md
- mkdocs.yml
- Added `Request-IlaMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Operations for Logs.
- Added `Request-IomMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Operations.
- Added `Request-PcaMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Automation.
- Updated Documentation.
> feat: aria certs and version

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-PdrDeployment` cmdlet where expeted errors are thrown to the output making it look like a failure when in fact the task completes.
N/A
N/A
> fix: add network adapter error output

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Enable-vRLIContentPack` cmdlet to handle invalid Git Hub tokens, and additional checks to ensure content pack URL is obtained.
> feat: enhance enable-vrlicontentpack

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- config.PowerValidatedSolutions
- docs/documentation/functions/aria-suite/aria-operations-networks/Request-AriaNetworksToken.md
- docs/documentation/functions/solutions/inv/Test-InvPrerequisite.md
- docs/documentation/functions/solutions/inv/index.md
- mkdocs.yml
- Added `Test-InvPrerequisite` cmdlet to verify prerequisites for Intelligent Network Visibility.
N/A
N/A
> feat: add inv prerequsite option

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Deploy-PhotonAppliance` cmdlet to pull the primary datastore and cluster details from SDDC Manager.
N/A
N/A
> fix: deploy hrm photon appliance

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/inv/Request-InvMscaSignedCertificate.md
- docs/documentation/functions/solutions/inv/index.md
- mkdocs.yml
- Added `Request-InvMscaSignedCertificate` cmdlet to request a signed certificate from a Microsoft Certificate Authority for VMware Aria Operations for Networks.
N/A
N/A
> feat: add inv cert creation

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Switched `Enable-vRLIContentPack` for Workspace ONE Access back to a manual step.
N/A
N/A
> chore: switch wsa content pack to manual

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations/Request-vROpsLogForwardingConfig.md
- docs/documentation/functions/solutions/hrm/Deploy-PhotonAppliance.md
- mkdocs.yml
- Fixed `Update-vROPSAdapterCollecterGroup` where there was an issue updating the adaptor.
- Fixed `Request-vROpsLogForwardingConfig` where no connection was being made to VMware Aria Operations.
- Enhanced `Deploy-PhotonAppliance` to retrieve the management portgroup automatically.
N/A
> fix: issues with solution interop of aria operations for logs

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fix: remove portgroup from deploy-photonappliance)
> fix: remove portgroup from deploy-photonappliance

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Install-vRSLCMCertificate` cmdlet to perform additonal checks that a Microsoft Certificate Authority is configured in SDDC Manager.
- Enhanced `Install-vRSLCMCertificate` cmdlet to perform additonal checks that a Microsoft Certificate Authority is configured in SDDC Manager.
N/A
> feat: enhance install-vrslcmcertificate pre-check

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/ila/Invoke-IlaSolutionInterop.md
- docs/documentation/functions/solutions/ila/Invoke-UndoIlaSolutionInterop.md
- docs/documentation/functions/solutions/ila/index.md
- mkdocs.yml
- Added `Invoke-IlaSolutionInterop` cmdlet to perform solution interoperability configuration for Intelligent Logging and Analytics.
- Added `Invoke-UndoIlaSolutionInterop` cmdlet to perform the removal of solution interoperability configuration for Intelligent Logging and Analytics.
N/A
> feat: add solution interop for ila

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/ila/index.md
- docs/documentation/functions/solutions/iom/Invoke-IomSolutionInterop.md
- docs/documentation/functions/solutions/iom/Invoke-UndoIomSolutionInterop.md
- docs/documentation/functions/solutions/iom/index.md
- mkdocs.yml
- Added `Invoke-IomSolutionInterop` cmdlet to perform solution interoperability configuration for Intelligent Operations Management.
- Added `Invoke-UndoIomSolutionInterop` cmdlet to perform the removal of solution interoperability configuration for Intelligent Operations Management.
N/A
> feat: add iom solution interop

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/inv/Invoke-InvSolutionInterop.md
- docs/documentation/functions/solutions/inv/Invoke-UndoInvSolutionInterop.md
- docs/documentation/functions/solutions/inv/index.md
- docs/documentation/functions/solutions/iom/Invoke-IomSolutionInterop.md
- mkdocs.yml
- Added `Invoke-InvSolutionInterop` cmdlet to perform solution interoperability configuration for Intelligent Network Visibility.
- Added `Invoke-UndoInvSolutionInterop` cmdlet to perform the removal of solution interoperability configuration for Intelligent Network Visibility.
N/A
> feat: add inv solution interop

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/cbw/Invoke-CbwSolutionInterop.md
- docs/documentation/functions/solutions/cbw/Invoke-UndoCbwSolutionInterop.md
- docs/documentation/functions/solutions/cbw/index.md
- mkdocs.yml
- Added `Invoke-CbwSolutionInterop` cmdlet to perform solution interoperability configuration for Cloud-Based Workload Protection.
- Added `Invoke-UndoCbwSolutionInterop` cmdlet to perform the removal of solution interoperability configuration for Cloud-Based Workload Protection.
N/A
> feat: add cbw solution interop

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/New-AriaNetworksvCenterDataSource.md
- docs/documentation/functions/aria-suite/aria-operations-networks/Remove-AriaNetworksDataSource.md
- mkdocs.yml
- Added `Remove-AriaNetworksDataSource` cmdlet to remove a data source from VMware Aria Operations for Networks.
- Added `New-AriaNetworksvCenterDataSource` cmdlet to add a vCenter Server in VMware Aria Operations for Networks.
> feat: add-inv-functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-automation/New-vRAvROPSIntegrationItem.md
- docs/documentation/functions/aria-suite/aria-operations/Update-vROPSvRAAdapterCredential.md
- docs/documentation/functions/solutions/iom/index.md
- docs/documentation/functions/solutions/pca/Invoke-PcaSolutionInterop.md
- docs/documentation/functions/solutions/pca/Invoke-UndoPcaSolutionInterop.md
- docs/documentation/functions/solutions/pca/index.md
- mkdocs.yml
- Added `Invoke-PcaSolutionInterop` cmdlet to perform solution interoperability configuration for Private Cloud Automation.
- Added `Invoke-UndoPcaSolutionInterop` cmdlet to perform the removal of solution interoperability configuration for Private Cloud Automation.
- Fixed `Get-vRAIntegrationDetail` cmdlet where by it was passing output incorrectly.
- Enhanced `New-vRAvROPSIntegrationItem` cmdlet for better error checking and message handling.
- Enhanced `Undo-vRAvROPsIntegrationItem` cmdlet for better error checking and message handling.
- Enhanced `Update-vROPSvRAAdapterCredential` cmdlet to reduce the number of inputs required.
- Added Documentation
N/A
> feat: add pca solution interop

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/pdr/Invoke-PdrSolutionInterop.md
- docs/documentation/functions/solutions/pdr/Invoke-UndoPdrSolutionInterop.md
- docs/documentation/functions/solutions/pdr/index.md
- docs/documentation/functions/vsphere/Undo-SsoUser.md
- mkdocs.yml
- Added `Invoke-PdrSolutionInterop` cmdlet to perform solution interoperability configuration for Site Protection and Disaster Recovery.
- Added `Invoke-UndoPdrSolutionInterop` cmdlet to perform the removal of solution interoperability configuration for Site Protection and Disaster Recovery.
- Added `Undo-SsoUser` cmdlet to support removing a user from vCenter Single Sign-On.
- Added Documentation
N/A
> feat: add pdr solution interop

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added PowerValidaredSolution version to menu header.
N/A
> chore: improvement to menu output

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added initial folder placement into the JSON spec for VMware Aria Operations.
N/A
> feat: add folder placement for iom

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/New-AriaNetworksNsxtDataSource.md
> refactor: update inv functions

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Removed Cloud-Based Workload Protection from main menu.
N/A
> chore: remove cbw menu

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Invoke-DriDeployment` cmdlet to support v1.26 for Tanzu distribution.
N/A
> feat: increase tanzu distrubution support

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Update-AriaNetworksvCenterDataSourceCredentials.md
- mkdocs.yml
Added `Update-AriaNetworksvCenterDataSourceCredentials` cmdlet to update the credentials for a vCenter Server in VMware Aria Operations for Networks.
> feat: add-inv-function

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Update-AriaNetworksNsxtDataSourceCredentials.md
- mkdocs.yml
Added `Update-AriaNetworksNsxtDataSourceCredentials` cmdlet to update the credentials for a NSX Manager in VMware Aria Operations for Networks.
> feat: add inv function

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Register-vROPSManagementPack` cmdlet to handle the new VCFDiagnostics management pack in VMware Aria Operations.
Closes #665
> feat: enhance Register-vROPSManagementPack to handle VCFDiagnostics

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Removed commented out code from Invoke-DriDeployment.
- Verified fix for #470 
Closes #470
> chore: code clean up on dri

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Add-AriaNetworksVcenterDataSource.md
- docs/documentation/functions/aria-suite/aria-operations-networks/Test-AriaNetworksAuthentication.md
- docs/documentation/functions/aria-suite/aria-operations-networks/Test-AriaNetworksConnection.md
- docs/documentation/functions/aria-suite/aria-operations-networks/Undo-AriaNetworksVcenterDataSource.md
- docs/documentation/functions/solutions/inv/index.md
- mkdocs.yml
- Added `Test-AriaNetworksConnection` cmdlet to test network connectivity with a VMware Aria Operations for Networks instance.
- Added `Test-AriaNetworksAuthentication` cmdlet to test authentication with a VMware Aria Operations for Networks instance.
- Added `Add-AriaNetworksVcenterDataSource` cmdlet to add vCenter Server data sources to a VMware Aria Operations for Networks instance.
- Added `Undo-AriaNetworksVcenterDataSource` cmdlet to remove vCenter Server data sources from a VMware Aria Operations for Networks instance.
- Added documentation for all news functions.
> feat: add vcenter data source to inv

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Get-AriaNetworksLdapConfiguration.md
- mkdocs.yml
- Added `Get-AriaNetworksLdapConfiguration` cmdlet to get the LDAP configuration in VMware Aria Operations for Networks.
> feat:add-inv-functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-networks/Request-AriaNetworksInternalApi.md
- mkdocs.yml
- Added `Request-AriaNetworksInternalApi` cmdlet to send a request to an internal API endpoint in VMware Aria Operations for Networks.
> feat:add-inv-function

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleNotifications/aria-operations-notifications-srm.json
- SampleNotifications/aria-operations-notifications-vcf.json
- docs/documentation/functions/aria-suite/aria-operations/Import-vROPSNotification.md
- docs/documentation/functions/aria-suite/aria-operations/New-vROPSNotification.md
- Enhanced `New-vROPSNotification` cmdlet to consume a JSON file and pass new parameters.
- Enhanced `Import-vROPSNotification` cmdlet to consume a JSON file and pass new parameters.
- Updated to `Invoke-IomDeployment` menu titles.
- Updated documentation.
> feat: add parameters to import-vropsnotification

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Invoke-GlobalWsaDeployment` cmdlet to ensure that the Workspace ONE Access identity provider is referencing the cluster FQDN.
> feat: configure idp hostname with cluster fqdn

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-InvJsonSpec` cmdlet to export additional fields into the json file.
> refactor:update-inv-functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- SampleNotifications/aria-operations-notifications-srm.json
- SampleNotifications/aria-operations-notifications-vcf.json
- Enhanced `Invoke-UndoIomDeployment` cmdlet to remove the load balancer configured in VMware Aria Suite Lifecycle for VMware Aria Operations.
- Enhanced `Invoke-UndoPcaDeployment` cmdlet to remove the load balancer configured in VMware Aria Suite Lifecycle for VMware Aria Automation.
> feat: remove load balancer for automation and ops undo

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Get-WSADirectory` cmdlet where url for Workspace ONE Access was hardcoded.
> fix: Get-WSADirectory

- CHANGELOG.md
- docs/index.md
- docs/requirements.txt
- docs/snippets/copy-module-local-windows.ps1
- docs/snippets/install-module.ps1
- docs/snippets/save-module-local-windows.ps1
Documentation preparations for the v2.11.0 release.
> docs: release preparations

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Adds the installation of the Workspace ONE Access content pack to `Invoke-IlaDeployment`.
> feat: install content pack

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Updates to `Export-PdrJsonSpec` cmdlet to support old and new named cells in the PnP
- replicationSubnet
- replicationGateway
- Fixed `Export-PdrJsonSpec` cmdlet where brackets were missing around the -as [Int]
> fix: address pnp named cell changes

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Invoke-InvDeployment` cmdlet to remove the need for WSA and add in the Admin VRSLCM Password to the Locker.
Closes #703
> refactor: inv wrapper functions

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
Enhanced `Get-LocalAccountLockout` cmdlet to return null values as "Not Configured" when a setting is not configured in an appliance.
Closes #702
> feat: update `Get-LocalAccountLockout` to return status instead of null

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/solutions/hrm/Deploy-PhotonAppliance.md
- Enhanced `Deploy-PhotonAppliance` cmdlet with an input parameter for the portgroup to attach the Virtual Machine too.
Closes #681
> feat: hrm deployment to correct portgroup

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/site-recovery-manager/Install-SiteRecoveryManager.md
- docs/documentation/functions/vsphere-replication/Install-vSphereReplicationManager.md
- Enhanced `Export-PdrJsonSpec` cmdlet to export the management VM portgroup from the Planning and Preparation Workbook.
- Enhanced `Install-vSphereReplicationManager` cmdlet to require a portgroup as an input.
- Enhanced `Install-SiteRecoveryManager` cmdlet to require a portgroup as an input.
- Enhanced `Invoke-PdrDeployment` cmdlet to pass the new portgroup parameter to `Install-vSphereReplicationManager` and `Install-SiteRecoveryManager`.
- Updated documentation.
> fix: pdr deployment of appliances

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Export-PdrJsonSpec` cmdlet to extract the range of replication IPs based on the populated Planning and Preparation workbook.
Closes #706
> fix: replication ips for vsphere replication

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Write-MenuHeader` cmdlet with updated global variable coming from VMware.PlatformTools.
> fix: global property change in pt

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Removed Alias `Request-NsxToken` from `Request-NsxtToken` cmdlet.
> chore: remove alias for request-nsxttoken

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Added DNS entries pre-checks to the `Test-VrslcmPrerequisite` cmdlet to ensure all assocated DNS entries are resolvable for both forward and reverse lookups.
- Added DNS entries pre-checks to the `Test-GlobalWsaPrerequisite` cmdlet to ensure all assocated DNS entries are resolvable for both forward and reverse lookups.
- Added DNS entries pre-checks to the `Test-IlaPrerequisite` cmdlet to ensure all assocated DNS entries are resolvable for both forward and reverse lookups.
- Added DNS entries pre-checks to the `Test-IomPrerequisite` cmdlet to ensure all assocated DNS entries are resolvable for both forward and reverse lookups.
- Added DNS entries pre-checks to the `Test-PcaPrerequisite` cmdlet to ensure all assocated DNS entries are resolvable for both forward and reverse lookups.
- …
> feat:add-prereq-dns-checks

- CHANGELOG.md
- docs/documentation/functions/nsx/Remove-NsxtGlobalManagerStandby.md
- docs/documentation/functions/nsx/Undo-NsxtGlobalManagerStandby.md
- docs/documentation/functions/solutions/fed/index.md
- mkdocs.yml
- Added documentation for `Remove-NsxtGlobalManagerStandby`.
- Added documentation for `Undo-NsxtGlobalManagerStandby`.
> chore: documentation updates

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Start-InvMenu` cmdlet with typo error.
> fix: typo on inv menu

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Invoke-IamDeployment` cmdlet when an isolated workload domain was deployed assigning global permissions was failing.
Closes #728
> fix: isolated domain issue for iam

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/nsx/Get-NsxtGlobalManagerTier0LocaleServices.md
- docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0Gateway.md
- docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0LocaleServices.md
- docs/documentation/functions/nsx/Undo-NsxtGlobalManagerTier0Gateway.md
- docs/documentation/functions/solutions/fed/index.md
- mkdocs.yml
> chore: add missing documentation

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/nsx/Export-NsxtGlobalManagerTier0GatewayConfig.md
- docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0BgpNeighborConfig.md
- docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0ServiceInterface.md
- docs/documentation/functions/nsx/Update-NsxtGlobalManagerTier1Gateway.md
- mkdocs.yml
- Updated `Invoke-NsxFederationDeployment` with `Undo-NsxtGlobalManagerTier0Gateway` procedure.
- Added Documentation.
> feat: Connect Additional Instances to Cross-Instance Tier-0 Gateway

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/aria-suite/aria-operations-logs/Add-vRLISmtpConfiguration.md
- Enhanced `Add-vRLISmtpConfiguration` cmdlet to perform multiple attempts at checking the configuration is applied correctly before failing.
- Updated Documentation.
> feat: enhancements to Add-vRLISmtpConfiguration

- PowerValidatedSolutions.psd1
- config.PowerValidatedSolutions
- Updated `config.PowerValidatedSolutions` to support VMware Cloud Foundation 5.2.1
> feat: add support for vcf 521

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- docs/documentation/functions/nsx/Add-NsxtGlobalManagerCertificate.md
- docs/documentation/functions/nsx/Get-NsxtGlobalManagerCertificate.md
- docs/documentation/functions/nsx/Get-NsxtGlobalManagerCertificateResult.md
- docs/documentation/functions/nsx/Import-NsxtGlobalManagerCertificate.md
- docs/documentation/functions/nsx/Install-NsxtGlobalManagerCertificate.md
- docs/documentation/functions/nsx/Test-NsxtGlobalManagerCertificate.md
- mkdocs.yml
- Updated `Invoke-NsxFederationDeployment` cmdlet to include `Install-NsxtGlobalManagerCertificate` cmdlet.
- Added Documentation
> feat: global manager cert replacement

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Adjusted menu to put NSX Federation fist.
> feat: nsx feration testing

- CHANGELOG.md
- config.PowerValidatedSolutions
- docs/index.md
- docs/snippets/install-module.ps1
Updates `VMware.PowerCLI` from 13.2.1 to 13.3.0.
> chore(deps): bump `VMware.PowerCLI` from 13.2.1 to 13.3.0

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- config.PowerValidatedSolutions
- docs/index.md
Updates `Import-Excel` from 7.8.5 to 7.8.9.
> chore(deps): bump `Import-Excel` from 7.8.5 to 7.8.9

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-NetworkSegment` cmdlet to return the pre-validation error correctly (removed breaks in the code).
> feat: remove breaks from add-networksegment

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- config.PowerValidatedSolutions
- Enhanced `config.PowerValidatedSolutions` configuration file to include NSX version so be able to check for the binary for NSX Federation.
> feat: nsx ova enhancement

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-vROPSAdapterVcf` cmdlet updated to provide additional output on progress.
> feat: enhance output and error handling for add-vropsadaptervcf

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-vCenterGlobalPermission` cmdlet to force synchronization of global permissions.
> feat: enhancement to Add-vCenterGlobalPermission

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Set-WorkspaceOneNtpConfig` cmdlet to handle a single NTP server.
> feat: enhancement to Set-WorkspaceOneNtpConfig

- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Fixed `Export-PdrJsonSpec` cmdlet where it pulling the wrong IP addresses for ESXi replication.
> fix: pdr json generation issue

- CHANGELOG.md
- PowerValidatedSolutions.psd1
- PowerValidatedSolutions.psm1
- Enhanced `Add-vROPSAdapterVcf` cmdlet updated to provide additional output on progress and checks on configuration process.
> feat: enhance Add-vROPSAdapterVcf

- PowerValidatedSolutions.psd1
- config.PowerValidatedSolutions
- Updated `config.PowerValidatedSolutions` to support latest Aria versions for older VCF releases.
> chore: updated aria versions for older vcf releases
